;;; tategaki-corpus-integration-test.el --- Cross-document RAG lifecycle checks -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'tategaki-assistant)
(require 'tategaki-studio)
(unless (featurep 'tategaki-corpus-test)
  (load (expand-file-name "tategaki-corpus-test.el"
                          (file-name-directory (or load-file-name buffer-file-name))) nil nil t))

(ert-deftest tategaki-corpus-integration-rag-includes-manuscripts-and-legacy-resources ()
  (tategaki-corpus-test--isolated
    (tategaki-corpus-register sea 'manuscript)
    (make-directory (expand-file-name ".tategaki/resources/" directory) t)
    (with-temp-file (expand-file-name ".tategaki/resources/legacy.txt" directory)
      (insert "海についての既存資料。"))
    (let ((text (buffer-string)) (undo buffer-undo-list) result)
      (tategaki-rag-context "海" (lambda (r) (setq result r)))
      (should (plist-get result :ok))
      (should (string-match-p "原稿:sea.txt:" (plist-get result :text)))
      (should (string-match-p "資料:legacy.txt:" (plist-get result :text)))
      (should (equal text (buffer-string)))
      (should (eq undo buffer-undo-list)))))

(ert-deftest tategaki-corpus-integration-cutoff-or-character-never-queries-other-files ()
  (tategaki-corpus-test--isolated
    (tategaki-corpus-register sea 'manuscript)
    (require 'tategaki-knowledge)
    (cl-letf (((symbol-function 'tategaki-corpus-retrieve) (lambda (&rest _) (ert-fail "cross-document query")))
              ((symbol-function 'tategaki-rag-resource-chunks) (lambda () (ert-fail "legacy resources leaked")))
              ((symbol-function 'tategaki-knowledge-filter-chunks) (lambda (chunks &rest _) chunks)))
      (dolist (scope '((5 nil) (nil "花子") (5 "花子")))
        (let (result)
          (tategaki-rag-context "海" (lambda (r) (setq result r)) (car scope) nil (cadr scope))
          (should (plist-get result :ok))
          (should-not (string-match-p "海を渡る" (plist-get result :text))))))))

(ert-deftest tategaki-corpus-integration-rag-cancels-pending-query-and-late-callback ()
  (tategaki-corpus-test--isolated
    (tategaki-corpus-register sea)
    (tategaki-corpus-test--index)
    (let ((transport (generate-new-buffer " *corpus RAG pending*")) pending responses job)
      (cl-letf (((symbol-function 'tategaki-ai-embed)
                 (lambda (_ callback &optional _authorized)
                   (setq pending callback) transport)))
        (setq job (tategaki-rag-context "海" (lambda (r) (push r responses))))
        (should-not responses)
        (tategaki-rag-cancel job)
        (should-not (buffer-live-p transport))
        (should (= 1 (length responses)))
        (should-not (plist-get (car responses) :ok))
        (funcall pending '(:ok t :vectors ((1.0 0.0))))
        (should (= 1 (length responses)))))))

(ert-deftest tategaki-corpus-integration-assistant-cancels-synchronously-started-chat ()
  (tategaki-corpus-test--isolated
    (switch-to-buffer source)
    (let ((old (generate-new-buffer " *old RAG transport*"))
          (chat (generate-new-buffer " *current chat transport*")) panel pending)
      (unwind-protect
          (cl-letf (((symbol-function 'tategaki-rag-context)
                     (lambda (_ callback &rest _)
                       (funcall callback '(:ok t :chunks nil :method lexical :text "本文"))
                       old))
                    ((symbol-function 'tategaki-ai-chat)
                     (lambda (_ callback &optional _authorized) (setq pending callback) chat)))
            (setq panel (progn (tategaki-ask "海") (current-buffer)))
            (should (eq tategaki-assistant--transport chat))
            (should (= (length tategaki-assistant--transports) 2))
            (tategaki-assistant-cancel)
            (should-not (buffer-live-p old))
            (should-not (buffer-live-p chat))
            (funcall pending '(:ok t :text "遅れた回答"))
            (should-not (string-match-p "遅れた回答" (buffer-string))))
        (dolist (buffer (list panel old chat)) (when (buffer-live-p buffer) (kill-buffer buffer)))))))

(ert-deftest tategaki-corpus-integration-assistant-panel-kill-cancels-rag-job ()
  (tategaki-corpus-test--isolated
    (switch-to-buffer source)
    (tategaki-corpus-register sea)
    (tategaki-corpus-test--index)
    (let ((transport (generate-new-buffer " *pending corpus query*")) panel pending chat-called)
      (cl-letf (((symbol-function 'tategaki-ai-embed)
                 (lambda (_ callback &optional _authorized) (setq pending callback) transport))
                ((symbol-function 'tategaki-ai-chat) (lambda (&rest _) (setq chat-called t))))
        (tategaki-ask "海")
        (setq panel (current-buffer))
        (should tategaki-assistant--busy)
        (kill-buffer panel)
        (should-not (buffer-live-p transport))
        (funcall pending '(:ok t :vectors ((1.0 0.0))))
        (should-not chat-called)))))

(ert-deftest tategaki-corpus-integration-semantic-visit-supports-dirty-resource-and-unopened-manuscript ()
  (tategaki-corpus-test--isolated
    (tategaki-corpus-register sea 'manuscript)
    (let (chunk)
      (tategaki-corpus-retrieve "海" (lambda (r) (setq chunk (car (plist-get r :chunks)))))
      (should-not (get-file-buffer sea))
      (tategaki-semantic-visit chunk)
      (should (equal buffer-file-name sea))
      (should (= (point) (plist-get chunk :start)))
      (goto-char (point-max)) (insert "未保存の資料説明。")
      (let* ((text (buffer-string)) (undo buffer-undo-list)
             (live-chunk (car (tategaki-semantic-chunks))))
        (plist-put live-chunk :kind 'resource)
        (plist-put live-chunk :buffer nil)
        (tategaki-semantic-visit live-chunk)
        (should (equal text (buffer-string)))
        (should (eq undo buffer-undo-list))
        (should (buffer-modified-p))
        (insert "さらに変更。")
        (should-error (tategaki-semantic-visit live-chunk) :type 'user-error)))))

(ert-deftest tategaki-corpus-integration-duplicate-basenames-have-distinct-working-citations ()
  (dolist (kind '(resource manuscript))
    (tategaki-corpus-test--isolated
      (let ((first (expand-file-name "a/notes.txt" directory))
            (second (expand-file-name "b/notes.txt" directory))
            result panel)
        (make-directory (file-name-directory first) t)
        (make-directory (file-name-directory second) t)
        (with-temp-file first (insert "同じ章\n海の資料その一。"))
        (with-temp-file second (insert "同じ章\n海の資料その二。"))
        (tategaki-corpus-register first kind)
        (tategaki-corpus-register second kind)
        (tategaki-rag-context "海" (lambda (r) (setq result r)))
        (let* ((chunks (seq-filter (lambda (chunk) (member (plist-get chunk :document) (list first second)))
                                    (plist-get result :chunks)))
               (labels (mapcar (lambda (chunk) (plist-get chunk :citation)) chunks)))
          (should (= (length chunks) 2))
          (should (= (length (delete-dups (copy-sequence labels))) 2))
          (switch-to-buffer source)
          (setq panel (tategaki-assistant))
          (unwind-protect
              (progn
                (tategaki-assistant--write (string-join labels "\n") chunks)
                (dolist (chunk chunks)
                  (with-current-buffer panel
                    (goto-char (point-min))
                    (search-forward (plist-get chunk :citation))
                    (button-activate (button-at (1- (point)))))
                  (with-current-buffer (window-buffer (selected-window))
                    (should (equal buffer-file-name (plist-get chunk :document)))
                    (should (= (point) (plist-get chunk :start))))))
            (when (buffer-live-p panel) (kill-buffer panel))))))))

(ert-deftest tategaki-corpus-integration-exclusion-also-removes-legacy-resource ()
  (tategaki-corpus-test--isolated
    (let ((file (expand-file-name ".tategaki/resources/notes.txt" directory)) result)
      (make-directory (file-name-directory file) t)
      (with-temp-file file (insert "海の除外対象資料。"))
      (tategaki-corpus-register file)
      (tategaki-corpus-set-enabled file nil)
      (tategaki-rag-context "海" (lambda (r) (setq result r)))
      (should (plist-get result :ok))
      (should-not (string-match-p "除外対象" (plist-get result :text))))))

(ert-deftest tategaki-corpus-integration-pending-rag-rejects-legacy-edit-and-exclusion ()
  (dolist (change '(text exclusion))
    (tategaki-corpus-test--isolated
      (let ((file (expand-file-name ".tategaki/resources/notes.txt" directory)) pending result)
        (make-directory (file-name-directory file) t)
        (with-temp-file file (insert "海の資料。"))
        (tategaki-corpus-register file)
        (cl-letf (((symbol-function 'tategaki-semantic-retrieve)
                   (lambda (_ callback &rest _) (setq pending callback))))
          (tategaki-rag-context "海" (lambda (r) (setq result r))))
        (if (eq change 'text) (with-temp-file file (insert "海の変更済み資料。"))
          (tategaki-corpus-set-enabled file nil))
        (funcall pending '(:ok t :chunks nil :method lexical))
        (should-not (plist-get result :ok))
        (should-not (plist-get result :text))))))

(ert-deftest tategaki-corpus-integration-answer-disables-citations-after-resource-edit-or-exclusion ()
  (dolist (change '(text exclusion))
    (tategaki-corpus-test--isolated
      (tategaki-corpus-register sea)
      (switch-to-buffer source)
      (let (panel pending)
        (unwind-protect
            (cl-letf (((symbol-function 'tategaki-ai-chat)
                       (lambda (_ callback &optional _authorized) (setq pending callback))))
              (tategaki-ask "海")
              (setq panel (current-buffer))
              (with-current-buffer source
                (if (eq change 'text) (with-temp-file sea (insert "改訂後"))
                  (tategaki-corpus-set-enabled sea nil)))
              (funcall pending '(:ok t :text "説明 [資料:sea.txt:1]"))
              (with-current-buffer panel
                (goto-char (point-min))
                (should (search-forward "原稿・資料が変わりました" nil t))
                (search-forward "[資料:sea.txt:1]")
                (should-not (button-at (1- (point))))))
          (when (buffer-live-p panel) (kill-buffer panel)))))))

(provide 'tategaki-corpus-integration-test)
;;; tategaki-corpus-integration-test.el ends here
