;;; tategaki-paging-test.el --- Vertical page movement checks -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'tategaki)

(defmacro tategaki-paging-test--with-text (text &rest body)
  "Run BODY with TEXT displayed in a three-column terminal page."
  (declare (indent 1))
  `(progn
     (skip-unless (not (display-graphic-p)))
     (save-window-excursion
       (delete-other-windows)
       (let ((source (generate-new-buffer " *Tategaki paging test*"))
             (tategaki-column-height 3)
             (tategaki-padding-top 0) (tategaki-padding-bottom 0)
             (tategaki-padding-left 0) (tategaki-padding-right 0)
             (tategaki-character-spacing 0)
             (tategaki-line-spacing (/ (window-body-width) 3)))
         (unwind-protect
             (progn
               (switch-to-buffer source)
               (text-mode)
               (insert ,text)
               (goto-char (point-min))
               (buffer-enable-undo)
               (setq buffer-undo-list nil)
               (set-buffer-modified-p nil)
               (tategaki-mode 1)
               ,@body)
           (when (buffer-live-p source)
             (with-current-buffer source
               (when (bound-and-true-p completion-in-region-mode)
                 (completion-in-region-mode -1))
               (tategaki-mode -1)
               (set-buffer-modified-p nil))
             (kill-buffer source)))))))

(defun tategaki-paging-test--command (command &optional count)
  "Run movement COMMAND with COUNT and its normal display post-command hook."
  (let ((this-command command))
    (funcall command count)
    (tategaki--post-command)))

(defun tategaki-paging-test--cursor-location ()
  "Return the cursor's actual terminal display column and row."
  (let* ((display tategaki--display-string)
         (index (text-property-any 0 (length display) 'cursor t display))
         (prefix (substring display 0 index))
         (last-newline (cl-position ?\n prefix :from-end t)))
    (should index)
    (list (string-width (substring prefix (if last-newline (1+ last-newline) 0)))
          (cl-count ?\n prefix))))

(ert-deftest tategaki-paging-full-pages-keep-visible-column-and-row ()
  (tategaki-paging-test--with-text (make-string 90 ?日)
    (goto-char 5)
    (tategaki-refresh)
    (let ((location (tategaki-paging-test--cursor-location)))
      (tategaki-paging-test--command #'tategaki-forward-page)
      (should (= (point) 14))
      (should (equal (tategaki-paging-test--cursor-location) location))
      (tategaki-paging-test--command #'tategaki-forward-page)
      (should (= (point) 23))
      (should (equal (tategaki-paging-test--cursor-location) location))
      (tategaki-paging-test--command #'tategaki-backward-page 2)
      (should (= (point) 5))
      (should (equal (tategaki-paging-test--cursor-location) location)))))

(ert-deftest tategaki-paging-short-last-page-restores-desired-column-and-row ()
  (tategaki-paging-test--with-text (make-string 22 ?日)
    (goto-char 9)
    (tategaki-refresh)
    (let ((location (tategaki-paging-test--cursor-location)))
      (tategaki-paging-test--command #'tategaki-forward-page)
      (should (= (point) 18))
      (tategaki-paging-test--command #'tategaki-forward-page)
      ;; Final page has two columns; its last column contains one char + EOF.
      (should (= (point) 23))
      (tategaki-paging-test--command #'tategaki-backward-page)
      (should (= (point) 18))
      (should (equal (tategaki-paging-test--cursor-location) location))
      (tategaki-paging-test--command #'tategaki-backward-page)
      (should (= (point) 9)))))

(ert-deftest tategaki-paging-short-column-keeps-desired-row-across-pages ()
  (tategaki-paging-test--with-text "abc\nabc\nabc\nx\nabc\nabc\nabc\n"
    (setq tategaki-column-height 4)
    (goto-char 3)
    (tategaki-refresh)
    (tategaki-paging-test--command #'tategaki-forward-page)
    (should (= (point) 14))
    (tategaki-paging-test--command #'tategaki-forward-page)
    (should (= (point) 25))
    (tategaki-paging-test--command #'tategaki-backward-page)
    (should (= (point) 14))
    (tategaki-paging-test--command #'tategaki-backward-page)
    (should (= (point) 3))))

(ert-deftest tategaki-paging-prefix-zero-negative-and-boundaries ()
  (tategaki-paging-test--with-text (make-string 40 ?日)
    (goto-char 5)
    (tategaki-refresh)
    (tategaki-paging-test--command #'tategaki-forward-page 0)
    (should (= (point) 5))
    (tategaki-paging-test--command #'tategaki-forward-page 2)
    (should (= (point) 23))
    (tategaki-paging-test--command #'tategaki-forward-page -1)
    (should (= (point) 14))
    (tategaki-paging-test--command #'tategaki-backward-page -1)
    (should (= (point) 23))
    (tategaki-paging-test--command #'tategaki-forward-page 1000000)
    (should (= (point) (point-max)))
    (tategaki-paging-test--command #'tategaki-forward-page)
    (should (= (point) (point-max)))
    (tategaki-paging-test--command #'tategaki-backward-page 1000000)
    (should (= (point) (point-min)))
    (tategaki-paging-test--command #'tategaki-backward-page)
    (should (= (point) (point-min)))))

(ert-deftest tategaki-paging-normal-motion-resets-page-and-row-goals ()
  (tategaki-paging-test--with-text (make-string 22 ?日)
    (goto-char 9)
    (tategaki-refresh)
    (tategaki-paging-test--command #'tategaki-forward-page 2)
    (should (= (point) 23))
    (tategaki-paging-test--command #'tategaki-previous-character 1)
    (should (= (point) 22))
    (tategaki-paging-test--command #'tategaki-backward-page)
    ;; New visual column/row after ordinary movement replaces the old goal.
    (should (= (point) 13))))

(ert-deftest tategaki-paging-column-motion-resets-page-goal-but-keeps-row ()
  (tategaki-paging-test--with-text (make-string 22 ?日)
    (goto-char 9)
    (tategaki-refresh)
    (tategaki-paging-test--command #'tategaki-forward-page 2)
    (tategaki-paging-test--command #'tategaki-backward-column)
    (should (= (point) 21))
    (tategaki-paging-test--command #'tategaki-backward-page)
    (should (= (point) 12))))

(ert-deftest tategaki-paging-resize-discards-incompatible-page-column-goal ()
  (tategaki-paging-test--with-text (make-string 22 ?日)
    (goto-char 9)
    (tategaki-refresh)
    (tategaki-paging-test--command #'tategaki-forward-page 2)
    (should (= (point) 23))
    ;; Keeping the original gap with one third of the width leaves one column/page.
    (split-window-right (/ (window-total-width) 3))
    (tategaki-refresh)
    (tategaki-paging-test--command #'tategaki-backward-page)
    ;; A changed page size resets both goals to the current cell (row one).
    (should (= (point) 20))))

(ert-deftest tategaki-paging-height-change-resets-goals-to-new-visible-cell ()
  (tategaki-paging-test--with-text (make-string 21 ?日)
    (goto-char 9)
    (tategaki-refresh)
    (tategaki-paging-test--command #'tategaki-forward-page 2)
    (should (= (point) 22))
    ;; Width/capacity stays fixed.  EOF moves from column seven, row zero
    ;; to column four, row one; the old desired offset/row was two/two.
    (setq tategaki-column-height 5)
    (tategaki-refresh)
    (let ((location (tategaki-paging-test--cursor-location)))
      (tategaki-paging-test--command #'tategaki-backward-page)
      (should (= (point) 7))
      (should (equal (tategaki-paging-test--cursor-location) location))
      (tategaki-paging-test--command #'tategaki-forward-page)
      (should (= (point) 22))
      (should (equal (tategaki-paging-test--cursor-location) location)))))

(ert-deftest tategaki-paging-empty-and-eof-only-page ()
  (tategaki-paging-test--with-text ""
    (tategaki-paging-test--command #'tategaki-forward-page)
    (tategaki-paging-test--command #'tategaki-backward-page)
    (should (= (point) 1))
    (should (tategaki-paging-test--cursor-location)))
  (tategaki-paging-test--with-text (make-string 9 ?日)
    (tategaki-paging-test--command #'tategaki-forward-page)
    (should (= (point) 10))
    (tategaki-paging-test--command #'tategaki-backward-page)
    (should (= (point) 1))))

(ert-deftest tategaki-paging-narrowing-native-region-and-source-invariants ()
  (let ((transient-mark-mode t))
    (tategaki-paging-test--with-text (propertize (make-string 90 ?日) 'face 'bold)
      (let ((original (buffer-string))
            (tick (buffer-chars-modified-tick))
            (undo buffer-undo-list))
        (narrow-to-region 10 70)
        (goto-char 14)
        (push-mark 11 t t)
        (tategaki-refresh)
        (let ((current-prefix-arg 2)
              (this-command #'tategaki-forward-page))
          (call-interactively #'tategaki-forward-page)
          (tategaki--post-command))
        (should (= (point) 32))
        (should (use-region-p))
        (should (= (mark) 11))
        (tategaki-paging-test--command #'tategaki-backward-page 1000)
        (should (= (point) 10))
        (tategaki-paging-test--command #'tategaki-forward-page 1000)
        (should (= (point) 70))
        (widen)
        (should (equal-including-properties original (buffer-string)))
        (should (= tick (buffer-chars-modified-tick)))
        (should (eq undo buffer-undo-list))
        (should-not (buffer-modified-p))))))

(ert-deftest tategaki-paging-keys-independent-of-physical-mode-and-restored-on-exit ()
  (let ((tategaki-physical-navigation nil))
    (tategaki-paging-test--with-text (make-string 30 ?日)
      (tategaki-mode -1)
      (use-local-map (make-sparse-keymap))
      (local-set-key (kbd "C-v") #'end-of-buffer)
      (local-set-key (kbd "M-v") #'beginning-of-buffer)
      (let* ((keys '("C-v" "M-v" "<next>" "<prior>"))
             (bindings (mapcar (lambda (key) (key-binding (kbd key))) keys)))
        (tategaki-mode 1)
        (should (equal (mapcar (lambda (key) (key-binding (kbd key))) keys)
                       '(tategaki-forward-page tategaki-backward-page
                         tategaki-forward-page tategaki-backward-page)))
        (with-temp-buffer
          (should (eq (key-binding (kbd "C-v")) #'scroll-up-command))
          (should (eq (key-binding (kbd "M-v")) #'scroll-down-command)))
        (tategaki-mode -1)
        (should (equal (mapcar (lambda (key) (key-binding (kbd key))) keys) bindings))))))

(ert-deftest tategaki-paging-corfu-retains-native-candidate-page-keys ()
  (skip-unless (require 'corfu nil t))
  (let ((tategaki-physical-navigation t)
        (corfu-auto nil))
    (tategaki-paging-test--with-text (make-string 30 ?日)
      (goto-char 3)
      (corfu-mode 1)
      (let ((completion-in-region-mode-predicate #'always))
        (unwind-protect
            (progn
              (corfu--setup 2 3 '("日日" "日月") nil)
              (should (eq (key-binding (kbd "C-v")) #'corfu-scroll-up))
              (should (eq (key-binding (kbd "M-v")) #'corfu-scroll-down))
              (should (eq (key-binding (kbd "<next>")) #'corfu-scroll-up))
              (should (eq (key-binding (kbd "<prior>")) #'corfu-scroll-down)))
          (when completion-in-region-mode (corfu-quit))))
      (should (eq (key-binding (kbd "C-v")) #'tategaki-forward-page))
      (should (eq (key-binding (kbd "M-v")) #'tategaki-backward-page)))))

(provide 'tategaki-paging-test)
;;; tategaki-paging-test.el ends here
