;;; tategaki-reading-test.el --- Diff and Reader state regressions -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later

(require 'ert)
(require 'cl-lib)
(require 'tategaki-diff)
(require 'tategaki-reader)
(require 'tategaki-highlight)
(require 'tategaki-diagnostics)

(ert-deftest tategaki-diff-marks-only-changed-lines-in-independent-copies ()
  (let ((old (generate-new-buffer " *test-old*"))
        (new (generate-new-buffer " *test-new*")) copies)
    (unwind-protect
        (save-window-excursion
          (with-current-buffer old (insert "共通\n旧稿\n結末\n")
                               (buffer-enable-undo) (goto-char 2))
          (with-current-buffer new (insert "共通\n新稿\n結末\n追記\n")
                               (buffer-enable-undo) (goto-char 3))
          (let ((old-text (with-current-buffer old (buffer-string)))
                (new-text (with-current-buffer new (buffer-string)))
                (old-undo (buffer-local-value 'buffer-undo-list old))
                (new-undo (buffer-local-value 'buffer-undo-list new)))
            (setq copies (tategaki-diff-buffers old new))
            (should (= 2 (length copies)))
            (with-current-buffer (car copies)
              (should buffer-read-only)
              (should (equal old-text (buffer-string)))
              (should (memq 'tategaki-diff-removed
                            (tategaki-highlight-faces 4 5 (get-buffer-window (current-buffer)))))
              (should-not (tategaki-highlight-faces 1 2 (get-buffer-window (current-buffer)))))
            (with-current-buffer (cadr copies)
              (should (equal new-text (buffer-string)))
              (should (= 2 (length tategaki-diff--overlays))))
            (with-current-buffer old
              (should (equal old-text (buffer-string)))
              (should (= (point) 2))
              (should (eq old-undo buffer-undo-list))
              (should (buffer-modified-p))
              (should-not (overlays-in (point-min) (point-max))))
            (with-current-buffer new
              (should (equal new-text (buffer-string)))
              (should (= (point) 3))
              (should (eq new-undo buffer-undo-list))
              (should (buffer-modified-p)))
            (with-current-buffer (car copies) (tategaki-diff-quit))
            (should-not (cl-some #'buffer-live-p copies))))
      (dolist (buffer (append copies (list old new)))
        (when (buffer-live-p buffer) (kill-buffer buffer))))))

(ert-deftest tategaki-diff-handles-empty-and-no-final-newline ()
  (should (equal (tategaki-diff--hunks "" "本文") '((0 0 1 1))))
  (should (equal (tategaki-diff--hunks "本文" "") '((1 1 0 0))))
  (should-not (tategaki-diff--hunks "同じ\n本文" "同じ\n本文")))

(ert-deftest tategaki-diff-navigation-uses-overlay-positions ()
  (with-temp-buffer
    (insert "一\n二\n三\n四\n")
    (tategaki-diff--mark-lines 2 1 'tategaki-diff-added)
    (tategaki-diff--mark-lines 4 1 'tategaki-diff-added)
    (goto-char 1)
    (tategaki-diff-next-change)
    (should (= (point) 3))
    (tategaki-diff-next-change)
    (should (= (point) 7))
    (tategaki-diff-next-change t)
    (should (= (point) 3))))

(ert-deftest tategaki-scene-branch-copies-region-and-records-whole-source ()
  (let* ((directory (make-temp-file "tategaki-branch-test-" t))
         (tategaki-history-directory directory)
         copy)
    (unwind-protect
        (save-window-excursion
          (with-temp-buffer
            (insert "最初\n別案の場面\n最後")
            (let ((text (buffer-string)) (transient-mark-mode t)
                  (source (current-buffer)))
              (goto-char 4) (set-mark 9) (activate-mark)
              (setq copy (tategaki-scene-branch "場面 B"))
              (with-current-buffer copy
                (should-not buffer-file-name)
                (should (buffer-modified-p))
                (should (equal (buffer-string) "別案の場面"))
                (should (equal text (tategaki-history--snapshot-text
                                     (plist-get tategaki-scene-branch-origin :snapshot)))))
              (with-current-buffer source (should (equal text (buffer-string)))))))
      (when (buffer-live-p copy) (kill-buffer copy))
      (delete-directory directory t))))

(ert-deftest tategaki-reader-roundtrip-restores-ui-locals-and-source ()
  (save-window-excursion
    (with-temp-buffer
      (switch-to-buffer (current-buffer))
      (buffer-enable-undo) (insert "原稿の本文\n次の段落")
      (goto-char 3) (set-mark 2)
      (setq-local header-line-format "original header")
      (setq-local mode-line-format "original status")
      (setq-local tategaki-manuscript-size '(20 . 20))
      (setq-local tategaki-manuscript-spread nil)
      (setq-local tategaki-manuscript-grid t)
      (setq-local tategaki-manuscript-fit-window nil)
      (setq-local tategaki-typesetting nil)
      (setq-local tategaki-studio-state 'review)
      (let ((text (buffer-string)) (undo buffer-undo-list)
            (other (get-buffer-create " *reader-side-test*")))
        (unwind-protect
            (progn
              (display-buffer-in-side-window other '((side . right)))
              (tategaki-reader-mode 1)
              (should buffer-read-only)
              (should (= 1 (length (window-list))))
              (should (equal tategaki-manuscript-size '(40 . 17)))
              (should tategaki-manuscript-spread)
              (should tategaki-manuscript-fit-window)
              (should tategaki-typesetting)
              (should-not mode-line-format)
              (should-not tategaki-diagnostics-visible)
              (goto-char 5)
              (tategaki-reader-mode -1)
              (should-not buffer-read-only)
              (should (equal header-line-format "original header"))
              (should (equal mode-line-format "original status"))
              (should (equal tategaki-manuscript-size '(20 . 20)))
              (should-not tategaki-manuscript-spread)
              (should tategaki-manuscript-grid)
              (should-not tategaki-manuscript-fit-window)
              (should-not tategaki-typesetting)
              (should (eq tategaki-studio-state 'review))
              (should tategaki-diagnostics-visible)
              (should (get-buffer-window other))
              (should (= (point) 3)) (should (= (mark) 2))
              (should (equal text (buffer-string)))
              (should (eq undo buffer-undo-list))
              (should (buffer-modified-p)))
          (tategaki-reader-mode -1)
          (kill-buffer other))))))

(ert-deftest tategaki-reader-retains-original-readonly-and-localness ()
  (save-window-excursion
    (with-temp-buffer
      (switch-to-buffer (current-buffer))
      (insert "本文")
      (setq buffer-read-only t)
      (kill-local-variable 'tategaki-manuscript-size)
      (kill-local-variable 'tategaki-manuscript-fit-window)
      (let ((was-local (local-variable-p 'tategaki-manuscript-size)))
        (tategaki-reader-mode 1)
        (should tategaki-manuscript-fit-window)
        (tategaki-reader-mode -1)
        (should buffer-read-only)
        (should-not (local-variable-p 'tategaki-manuscript-fit-window))
        (should-not tategaki-manuscript-fit-window)
        (should (eq was-local (local-variable-p 'tategaki-manuscript-size)))))))

(ert-deftest tategaki-reader-restores-explicit-whole-paper-fitting ()
  (save-window-excursion
    (with-temp-buffer
      (switch-to-buffer (current-buffer))
      (insert "既存の全体表示設定を保持")
      (setq-local tategaki-manuscript-fit-window t)
      (tategaki-reader-mode 1)
      (should tategaki-manuscript-fit-window)
      (tategaki-reader-mode -1)
      (should (local-variable-p 'tategaki-manuscript-fit-window))
      (should tategaki-manuscript-fit-window))))

(ert-deftest tategaki-reader-hides-and-restores-existing-diagnostic-overlays ()
  (save-window-excursion
    (with-temp-buffer
      (switch-to-buffer (current-buffer))
      (insert "本文です")
      (let ((overlay (make-overlay 1 3)))
        (overlay-put overlay 'tategaki-diagnostic '(:severity warning :message "test"))
        (overlay-put overlay 'face 'tategaki-diagnostic-warning)
        (setq-local tategaki-diagnostics--overlays (list overlay))
        (tategaki-reader-mode 1)
        (should (overlay-buffer overlay))
        (should-not (overlay-get overlay 'face))
        (tategaki-reader-mode -1)
        (should (overlay-buffer overlay))
        (should (overlay-get overlay 'face))))))

(ert-deftest tategaki-reader-invalid-preset-rolls-back-state ()
  (save-window-excursion
    (with-temp-buffer
      (insert "本文")
      (setq-local header-line-format "original")
      (let ((tategaki-reader-manuscript-size '(0 . 20)))
        (should-error (tategaki-reader-mode 1) :type 'user-error)
        (should-not tategaki-reader-mode)
        (should-not tategaki-reader--saved)
        (should-not buffer-read-only)
        (should (equal header-line-format "original"))))))

(provide 'tategaki-reading-test)
;;; tategaki-reading-test.el ends here
