;;; tategaki-paging-graphical-tests.el --- Page movement GUI checks -*- lexical-binding: t; -*-

;; Run in a dedicated Emacs process; exits after the tests.
(require 'ert)
(let* ((directory (file-name-directory (or load-file-name buffer-file-name)))
       (root (file-name-directory (directory-file-name directory))))
  (add-to-list 'load-path root)
  (setq load-prefer-newer t)
  (load (expand-file-name "test/tategaki-test.el" root) nil t t)
  (load (expand-file-name "test/tategaki-completion-test.el" root) nil t t))

(defun tategaki-paging-gui--cursor ()
  "Return point's real glyph origin and verify the native cursor is there."
  (let ((pixel (tategaki-position-pixel (point)))
        (cursor (window-cursor-info)))
    (should pixel)
    (should cursor)
    (should (= (plist-get pixel :x) (aref cursor 1)))
    (should (= (plist-get pixel :y) (aref cursor 2)))
    (should (<= (+ (plist-get pixel :y) (plist-get pixel :height))
                (window-body-height nil t)))
    (cons (plist-get pixel :x) (plist-get pixel :y))))

(ert-deftest tategaki-paging-gui-page-keys-preserve-physical-cell ()
  (tategaki-test--with-source (make-string 3000 ?文)
    (let ((tategaki-column-height 9)
          (tategaki-padding-top 13) (tategaki-padding-bottom 17)
          (tategaki-padding-left 11) (tategaki-padding-right 19)
          (tategaki-line-spacing 12) (tategaki-character-spacing 4))
      (tategaki-mode 1)
      (goto-char 24)
      (let ((origin (tategaki-paging-gui--cursor)) (start (point))
            (source-text (buffer-string)) (columns tategaki--page-size))
        (execute-kbd-macro (kbd "C-v"))
        (should (= tategaki--page columns))
        (should (> (point) start))
        (should (equal origin (tategaki-paging-gui--cursor)))
        (execute-kbd-macro (kbd "M-v"))
        (should (= (point) start))
        (should (equal origin (tategaki-paging-gui--cursor)))
        (execute-kbd-macro (kbd "<next> <next>"))
        (should (= tategaki--page (* 2 columns)))
        (should (equal origin (tategaki-paging-gui--cursor)))
        (execute-kbd-macro (kbd "<prior> <prior>"))
        (should (= (point) start))
        (should (equal source-text (buffer-string)))
        (should-not (buffer-modified-p))))))

(ert-deftest tategaki-paging-gui-short-final-page-roundtrip ()
  (tategaki-test--with-source (make-string 3000 ?文)
    (let ((tategaki-column-height 6))
      (tategaki-mode 1)
      (let ((columns tategaki--page-size))
        (delete-region (+ 2 (* 6 (+ columns 2))) (point-max))
        (goto-char (+ 4 (* 6 (- columns 2))))
        (let ((start (point)) (origin (tategaki-paging-gui--cursor)))
          (execute-kbd-macro (kbd "C-v"))
          (should (= tategaki--page columns))
          (should (= (point) (point-max)))
          (tategaki-paging-gui--cursor)
          (execute-kbd-macro (kbd "C-u 1 M-v"))
          (should (= (point) start))
          (should (equal origin (tategaki-paging-gui--cursor)))
          (execute-kbd-macro (kbd "C-u 99 C-v"))
          (should (= (point) (point-max)))
          (tategaki-paging-gui--cursor)
          (execute-kbd-macro (kbd "C-u 99 M-v"))
          (should (= (point) (point-min)))
          (tategaki-paging-gui--cursor))))))

(ert-deftest tategaki-paging-gui-resize-updates-page-width ()
  (let ((width (frame-width)) (height (frame-height)))
    (unwind-protect
        (tategaki-test--with-source (make-string 5000 ?文)
          (let ((tategaki-column-height nil)
                (tategaki-character-spacing 3) (tategaki-padding-top 11))
            (tategaki-mode 1)
            (goto-char 6)
            (execute-kbd-macro (kbd "C-v"))
            (set-frame-size (selected-frame) 42 18)
            (sit-for 0.1)
            (tategaki-refresh)
            (let ((origin (tategaki-paging-gui--cursor))
                  (start (point)) (page tategaki--page) (columns tategaki--page-size))
              (execute-kbd-macro (kbd "C-v"))
              (should (= tategaki--page (+ page columns)))
              (should (equal origin (tategaki-paging-gui--cursor)))
              (execute-kbd-macro (kbd "M-v"))
              (should (= (point) start))
              (tategaki-paging-gui--cursor))))
      (set-frame-size (selected-frame) width height))))

(ert-deftest tategaki-paging-gui-long-copilot-proposal-does-not-absorb-page ()
  (tategaki-completion-test--with-text (make-string 1000 ?文)
    (goto-char 2)
    (tategaki-refresh)
    (let ((expected (+ (point) (* 3 tategaki--page-size)))
          (source-text (buffer-string)) (proposal (make-string 2000 ?仮)))
      (copilot--display-overlay-completion proposal nil proposal 2 2)
      (should (eq tategaki--preview-kind 'copilot))
      (let ((current-prefix-arg 0))
        (call-interactively (key-binding (kbd "C-v"))))
      (should (eq tategaki--preview-kind 'copilot))
      (execute-kbd-macro (kbd "C-v"))
      (should-not (tategaki-completion-current))
      (should-not (copilot--overlay-visible))
      (should (= (point) expected))
      (should (equal source-text (buffer-string)))
      (should-not buffer-undo-list)
      (should-not (buffer-modified-p))
      (tategaki-paging-gui--cursor))))

(run-at-time 60 nil (lambda () (kill-emacs 2)))
(run-at-time
 1 nil
 (lambda ()
   (let ((status 2))
     (condition-case err
         (progn
           (unless (and (display-graphic-p) (fboundp 'window-cursor-info))
             (error "A graphical Emacs with window-cursor-info is required"))
           (delete-other-windows)
           (set-frame-size (selected-frame) 70 27)
           (let ((stats (ert-run-tests-batch "^tategaki-paging-gui-")))
             (setq status (if (and (= (ert-stats-completed-expected stats) 4)
                                   (zerop (ert-stats-skipped stats))) 0 1))))
       (error (message "Paging GUI setup failed: %S" err)))
     (with-current-buffer "*Messages*"
       (write-region (point-min) (point-max)
                     (expand-file-name "tategaki-paging-gui-tests.log" temporary-file-directory)))
     (kill-emacs status))))

;;; tategaki-paging-graphical-tests.el ends here
