;;; tategaki-lookup-graphical-tests.el --- Isolated installed Lookup GUI check -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
;; Dedicated Emacs -Q only: this runner starts a private server and exits.
(require 'ert)
(require 'cl-lib)
(require 'server)
(defvar tategaki-lookup-gui--directory (make-temp-file "/tmp/tategaki-lookup-gui-" t))
(setq server-name "tategaki-isolated-lookup-gui"
      server-socket-dir (expand-file-name "sockets" tategaki-lookup-gui--directory)
      user-emacs-directory (expand-file-name "userdata/" tategaki-lookup-gui--directory)
      load-prefer-newer t inhibit-startup-screen t)
(make-directory server-socket-dir t)
(set-file-modes server-socket-dir #o700)
(make-directory user-emacs-directory t)
(server-start)
(let ((directory (file-name-directory (or load-file-name buffer-file-name))))
  (add-to-list 'load-path (file-name-directory (directory-file-name directory))))
(add-to-list 'load-path (expand-file-name "~/Sync/emacs.d/lookup"))
(add-to-list 'load-path (expand-file-name "~/Sync/emacs.d/lookup-macos"))
(require 'lookup)
(require 'nmacos)
(require 'tategaki-lookup)
(require 'tategaki-settings)
(setq lookup-init-file (expand-file-name "lookup-init.el" tategaki-lookup-gui--directory)
      lookup-cache-file-name nil lookup-enable-splash nil
      lookup-search-agents '((nmacos))
      tategaki-project-default-file (expand-file-name "defaults.json" tategaki-lookup-gui--directory))

(defun tategaki-lookup-gui--click-close (buffer)
  "Use BUFFER's actual rendered close-control pixels to dispatch a click."
  (select-window (get-buffer-window buffer))
  (redisplay t)
  (let* ((window (selected-window)) (height (window-header-line-height window))
         (position
          (cl-loop for x from 0 below (window-pixel-width window) by 2
                   for pos = (posn-at-x-y x (max 1 (/ height 2)) window)
                   for object = (and pos (posn-string pos))
                   when (and object (get-text-property (cdr object) 'local-map (car object)))
                   return pos)))
    (should position)
    (should (eq (posn-area position) 'header-line))
    (let ((command (key-binding [header-line mouse-1] nil nil position)))
      (should (eq command #'tategaki-pane-close))
      (funcall command (list 'mouse-1 position)))
    (should-not (get-buffer-window buffer))
    (set-buffer (window-buffer (selected-window)))))

(ert-deftest tategaki-lookup-gui-native-panes-close-independently-and-reopen ()
  (let ((source (generate-new-buffer " *Lookup GUI manuscript*"))
        (ordinary-content (get-buffer-create lookup-content-buffer))
        (ordinary-info (get-buffer-create "*Entry Information*"))
        context settings content entry info help dictionaries)
    (unwind-protect
        (save-window-excursion
          (with-current-buffer ordinary-content (insert "ordinary content sentinel"))
          (with-current-buffer ordinary-info (insert "ordinary info sentinel"))
          (switch-to-buffer source)
          (text-mode) (buffer-enable-undo)
          (insert "原稿の猫について辞書を引く。未保存の本文。") (goto-char 5) (set-mark 3)
          (let ((text (buffer-string)) (undo buffer-undo-list) (position (point))
                (mark-position (mark)) settings-window)
            (setq settings (tategaki-settings) settings-window (get-buffer-window settings))
            (with-current-buffer source
              (setq content (tategaki-lookup-word "猫")
                    context tategaki-lookup--source-context))
            (setq entry (get-buffer (plist-get context :entry)))
            (should (buffer-live-p entry))
            (should (> (buffer-size content) 20))
            (dolist (buffer (list content entry))
              (should (buffer-local-value 'tategaki-pane--installed-header buffer))
              (should (eq (window-parameter (get-buffer-window buffer) 'window-side) 'right)))
            (select-window (get-buffer-window content))
            (lookup-content-update)
            (should (buffer-local-value 'tategaki-pane--installed-header content))
            (select-window (get-buffer-window entry))
            (lookup-entry-info)
            (setq info (window-buffer (plist-get context :sub)))
            (should-not (eq info ordinary-info))
            (should (buffer-local-value 'tategaki-pane--installed-header info))
            (tategaki-lookup-gui--click-close info)
            (should (get-buffer-window entry))
            (should-not (plist-get context :sub))
            (select-window (get-buffer-window entry))
            (lookup-entry-display-content)
            (select-window (get-buffer-window content))
            (lookup-content-help)
            (setq help (get-buffer (plist-get context :help)))
            (should (get-buffer-window source))
            (tategaki-lookup-gui--click-close help)
            (should (get-buffer-window entry))
            (should (get-buffer-window content))
            (select-window (get-buffer-window entry))
            (lookup-entry-select-dictionary)
            (setq dictionaries (get-buffer (plist-get context :select)))
            (should (get-buffer-window dictionaries))
            (should (buffer-local-value 'tategaki-pane--installed-header dictionaries))
            (tategaki-lookup-gui--click-close dictionaries)
            (should (get-buffer-window content))
            (with-current-buffer source (tategaki-lookup-word "猫"))
            (select-window (get-buffer-window entry))
            (lookup-entry-select-dictionary)
            (lookup-history-previous)
            (should (get-buffer-window entry))
            (should (buffer-local-value 'tategaki-pane--installed-header entry))
            (tategaki-lookup-gui--click-close entry)
            (should (get-buffer-window content))
            (should-not (plist-get context :main))
            (select-window (get-buffer-window content))
            (lookup-content-update)
            (lookup-content-entry-window)
            (should (eq (window-buffer (selected-window)) entry))
            (tategaki-lookup-gui--click-close entry)
            ;; A new search after closing its main window recreates that pane.
            (with-current-buffer source (tategaki-lookup-word "犬"))
            (should (get-buffer-window entry))
            (should (get-buffer-window content))
            (tategaki-lookup-gui--click-close content)
            (should (get-buffer-window entry))
            (select-window (get-buffer-window entry))
            (lookup-entry-display-content)
            (should (get-buffer-window content))
            (should (buffer-local-value 'tategaki-pane--installed-header content))
            (should (eq (get-buffer-window settings) settings-window))
            (with-current-buffer source
              (should (equal text (buffer-string))) (should (eq undo buffer-undo-list))
              (should (= position (point))) (should (= mark-position (mark)))
              (should (buffer-modified-p)))
            (with-current-buffer ordinary-content
              (should (equal (buffer-string) "ordinary content sentinel"))
              (should-not tategaki-pane--installed-header))
            (with-current-buffer ordinary-info
              (should (equal (buffer-string) "ordinary info sentinel"))
              (should-not tategaki-pane--installed-header))
            (should-not lookup-main-window)
            (should-not lookup-sub-window)
            (should-not lookup-current-session)
            (message "Lookup GUI: Entry, Content, Dictionary List, Help, Entry Information; source and ordinary Lookup preserved")))
      (dolist (buffer (append (plist-get context :buffers)
                              (list settings ordinary-content ordinary-info source)))
        (when (buffer-live-p buffer)
          (with-current-buffer buffer (set-buffer-modified-p nil))
          (kill-buffer buffer))))))

(add-hook 'emacs-startup-hook
          (lambda ()
            (run-at-time
             1 nil
             (lambda ()
               (let ((status 2))
                 (condition-case error-data
                     (progn
                       (unless (display-graphic-p) (error "GUI required"))
                       (set-frame-size nil 150 50)
                       (let ((stats (ert-run-tests-batch "^tategaki-lookup-gui-")))
                         (setq status (if (zerop (ert-stats-completed-unexpected stats)) 0 1))))
                   (error (message "Lookup GUI error: %S" error-data)))
                 (with-current-buffer "*Messages*"
                   (write-region (point-min) (point-max) "/tmp/tategaki-lookup-gui-tests.log"))
                 (kill-emacs status))))) t)
(add-hook 'kill-emacs-hook
          (lambda () (ignore-errors (delete-directory tategaki-lookup-gui--directory t))) t)
(run-at-time 90 nil (lambda () (kill-emacs 2)))
;;; tategaki-lookup-graphical-tests.el ends here
