;;; tategaki-pane-test.el --- Persistent pane close integration -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'ert)
(require 'cl-lib)
(require 'tategaki-pane)
(require 'tategaki-studio)
(require 'tategaki-review)
(require 'tategaki-world)
(require 'tategaki-timeline)
(require 'tategaki-foreshadow)
(require 'tategaki-voice)
(require 'tategaki-knowledge)
(require 'tategaki-diagnostics)
(require 'tategaki-outline)
(require 'tategaki-history)
(require 'tategaki-diff)
(require 'tategaki-settings)
(require 'tategaki-export)
(require 'tategaki-reader)

(defmacro tategaki-pane-test--source (&rest body)
  "Run BODY in an isolated manuscript; remove only buffers created by the test."
  (declare (indent 0) (debug t))
  `(let* ((directory (make-temp-file "tategaki-pane-test-" t))
          (default-directory (file-name-as-directory directory))
          (tategaki-project-default-file (expand-file-name "defaults.json" directory))
          (tategaki-history-directory (expand-file-name "history/" directory))
          (tategaki-session-file (expand-file-name "session.json" directory))
          (tategaki-export--jobs (make-hash-table :test #'equal))
          (tategaki-export--last-job nil)
          (before (buffer-list))
          (source (generate-new-buffer " *pane manuscript*")))
     (unwind-protect
         (save-window-excursion
           (delete-other-windows)
           (switch-to-buffer source)
           (text-mode)
           (setq buffer-file-name (expand-file-name "manuscript.txt" directory))
           (insert "第一章\n花子は赤い傘を見た。\n\n第二章\n物語は続く。\n")
           (goto-char 6) (set-mark 12)
           (buffer-enable-undo) (setq buffer-undo-list nil) (set-buffer-modified-p nil)
           ,@body)
       (dolist (buffer (cl-set-difference (buffer-list) before))
         (when (buffer-live-p buffer)
           (with-current-buffer buffer
             (let ((tategaki-settings--allow-kill t)
                   (kill-buffer-query-functions nil))
               (when-let* ((process (get-buffer-process buffer))) (delete-process process))
               (set-buffer-modified-p nil) (kill-buffer buffer)))))
       (delete-directory directory t))))

(defun tategaki-pane-test--source-state (source)
  "Capture manuscript state relevant to a close-only operation."
  (with-current-buffer source
    (list (buffer-string) (point) (mark t) buffer-undo-list (buffer-modified-p))))

(defun tategaki-pane-test--assert-source (source state)
  "Require SOURCE text, point, mark, Undo identity and modified flag to equal STATE."
  (with-current-buffer source
    (should (equal (buffer-string) (nth 0 state)))
    (should (= (point) (nth 1 state))) (should (equal (mark t) (nth 2 state)))
    (should (eq buffer-undo-list (nth 3 state)))
    (should (eq (buffer-modified-p) (nth 4 state)))))

(defun tategaki-pane-test--header-control (buffer)
  "Return BUFFER's actual persistent close string and check its mouse binding."
  (let* ((header (buffer-local-value 'header-line-format buffer))
         (control (and (listp header)
                       (cl-find-if (lambda (item) (and (stringp item)
                                                       (string-match-p "\\[閉じる\\]" item))) header))))
    (should control)
    (should (eq (lookup-key (get-text-property 0 'local-map control) [header-line mouse-1])
                #'tategaki-pane-close))
    control))

(defun tategaki-pane-test--click (window)
  "Dispatch the installed header action at WINDOW without selecting it first."
  (let* ((control (tategaki-pane-test--header-control (window-buffer window)))
         (command (lookup-key (get-text-property 0 'local-map control) [header-line mouse-1])))
    (funcall command (list 'mouse-1 (list window 'header-line '(2 . 2) 0)))))

(defun tategaki-pane-test--other-pane ()
  "Open a separate pane that a close operation must leave untouched."
  (let ((buffer (generate-new-buffer " *unrelated pane*")))
    (with-current-buffer buffer (insert "残すペイン\n"))
    (display-buffer-in-side-window buffer '((side . bottom) (slot . 9) (window-height . 0.2)))
    buffer))

(defun tategaki-pane-test--activate-button (buffer label)
  "Activate the real text button with LABEL in BUFFER."
  (with-current-buffer buffer
    (goto-char (point-min)) (search-forward label)
    (button-activate (button-at (1- (point))))))

(ert-deftest tategaki-pane-header-reinstall-preserves-original-once ()
  (with-temp-buffer
    (setq-local header-line-format '("既存ヘッダー" (:eval "状態")))
    (let ((original header-line-format))
      (tategaki-pane-install nil nil "pane")
      (tategaki-pane-install nil nil "pane")
      (should (eq tategaki-pane--original-header original))
      (should (eq (car (last header-line-format)) original))
      (should (= 1 (cl-count-if (lambda (item) (and (stringp item) (string-match-p "\\[閉じる\\]" item))) header-line-format)))
      (tategaki-pane-test--header-control (current-buffer))
      (setq-local header-line-format "新しいヘッダー")
      (tategaki-pane-install nil nil "pane")
      (should (equal tategaki-pane--original-header "新しいヘッダー")))))

(ert-deftest tategaki-pane-closes-clicked-unselected-pane-and-keeps-other-pane ()
  (tategaki-pane-test--source
    (insert "未保存の編集") (goto-char 6)
    (let* ((state (tategaki-pane-test--source-state source))
           (panel (generate-new-buffer " *pane target*"))
           (other (tategaki-pane-test--other-pane)))
      (with-current-buffer panel (special-mode) (tategaki-pane-install source nil "対象"))
      (let ((target (display-buffer-in-side-window panel '((side . right) (slot . 2)))))
        (select-window (get-buffer-window other))
        (should-not (eq (selected-window) target))
        (tategaki-pane-test--click target)
        (should-not (get-buffer-window panel))
        (should (buffer-live-p panel)) (should (get-buffer-window other))
        (should (eq (window-buffer (selected-window)) source)))
      (tategaki-pane-test--assert-source source state))))

(ert-deftest tategaki-pane-export-start-installs-close-without-stopping-job ()
  (tategaki-pane-test--source
    (let ((state (tategaki-pane-test--source-state source))
          (find-program (symbol-function 'executable-find))
          (tategaki-export-output-directory (expand-file-name "exports" directory))
          job)
      (unwind-protect
          (cl-letf (((symbol-function 'executable-find)
                     (lambda (name) (if (equal name "docker") "/mock/docker" (funcall find-program name))))
                    ((symbol-function 'tategaki-export--read-profile) (lambda (_) '((input) (metadata))))
                    ((symbol-function 'make-process)
                     (lambda (&rest args)
                       (make-pipe-process :name (plist-get args :name) :buffer (plist-get args :buffer) :noquery t))))
            (setq job (gethash (tategaki-export--start '("epub") "mock" 'buffer) tategaki-export--jobs))
            (let ((panel (get-buffer (plist-get job :buffer))))
              (tategaki-pane-test--header-control panel)
              (pop-to-buffer panel)
              (tategaki-pane-test--click (get-buffer-window panel))
              (should (buffer-live-p panel)) (should-not (get-buffer-window panel))
              (should (eq (plist-get job :state) 'running))
              (should (process-live-p (plist-get job :process)))
              (tategaki-pane-test--assert-source source state)))
        (when-let* ((path (plist-get job :snapshot-directory)))
          (when (file-directory-p path) (delete-directory path t)))))))

(ert-deftest tategaki-pane-real-studio-review-world-diagnostics-history-matrix ()
  (tategaki-pane-test--source
    (let ((state (tategaki-pane-test--source-state source)))
      (dolist (entry '((menu . tategaki-studio-menu) (review . tategaki-review)
                       (world . tategaki-world) (timeline . tategaki-timeline)
                       (foreshadow . tategaki-foreshadow) (voice . tategaki-voice)
                       (diagnostics . tategaki-diagnostics-list) (history . tategaki-history)
                       (knowledge . (lambda () (tategaki-knowledge-compare "花子")))))
        (ert-info ((format "Pane %s" (car entry)))
          (select-window (get-buffer-window source)) (set-buffer source)
          (let* ((result (funcall (cdr entry)))
                 (panel (cond ((bufferp result) result) ((windowp result) (window-buffer result))
                              (t (window-buffer (selected-window)))))
                 (window (get-buffer-window panel))
                 (other (tategaki-pane-test--other-pane)))
            (should-not (eq panel source)) (should window)
            (should (eq (buffer-local-value 'tategaki-pane-source panel) source))
            (select-window (get-buffer-window source))
            (tategaki-pane-test--click window)
            (should-not (get-buffer-window panel)) (should (get-buffer-window other))
            (should (buffer-live-p panel))
            (tategaki-pane-test--assert-source source state)
            (delete-window (get-buffer-window other)) (kill-buffer other)))))))

(ert-deftest tategaki-pane-welcome-has-close-without-source ()
  (tategaki-pane-test--source
    (tategaki-studio-welcome)
    (let ((panel (current-buffer)))
      (tategaki-pane-test--header-control panel)
      (tategaki-pane-test--click (get-buffer-window panel))
      (should-not (get-buffer-window panel)) (should (buffer-live-p panel)))))

(ert-deftest tategaki-pane-history-copies-and-branch-hide-dirty-text-without-killing ()
  (tategaki-pane-test--source
    (let ((record (tategaki-history-snapshot 'manual source))
          (state (tategaki-pane-test--source-state source)))
      (dolist (function '(tategaki-history-open tategaki-history-restore-as-copy))
        (select-window (get-buffer-window source)) (set-buffer source)
        (let ((panel (funcall function record)))
          (with-current-buffer panel
            (unless buffer-read-only (goto-char (point-max)) (insert "コピーだけの編集")))
          (let ((text (with-current-buffer panel (buffer-string)))
                (modified (buffer-modified-p panel)))
            (tategaki-pane-test--click (get-buffer-window panel))
            (should-not (get-buffer-window panel)) (should (buffer-live-p panel))
            (should (equal text (with-current-buffer panel (buffer-string))))
            (should (eq modified (buffer-modified-p panel))))))
      (select-window (get-buffer-window source)) (set-buffer source)
      (let ((copy (tategaki-scene-branch "pane branch")))
        (with-current-buffer copy (goto-char (point-max)) (insert "別案の編集"))
        (tategaki-pane-test--click (get-buffer-window copy))
        (should-not (get-buffer-window copy)) (should (buffer-live-p copy))
        (should (buffer-modified-p copy))
        (should (string-suffix-p "別案の編集" (with-current-buffer copy (buffer-string)))))
      (tategaki-pane-test--assert-source source state))))

(ert-deftest tategaki-pane-outline-close-cleans-source-hooks-timer-and-markers ()
  (tategaki-pane-test--source
    (let ((state (tategaki-pane-test--source-state source)))
      (tategaki-outline)
      (let ((panel (window-buffer (selected-window)))
            (other (tategaki-pane-test--other-pane)))
        (with-current-buffer source
          (should (memq #'tategaki-outline--after-change after-change-functions))
          (should (memq #'tategaki-outline--post-command post-command-hook))
          (setq tategaki-outline--timer (run-at-time 3600 nil #'ignore)))
        (select-window (get-buffer-window other))
        (tategaki-pane-test--click (get-buffer-window panel))
        (should-not (buffer-live-p panel)) (should (get-buffer-window other))
        (with-current-buffer source
          (should-not tategaki-outline--timer) (should-not tategaki-outline--buffer)
          (should-not tategaki-outline--entries)
          (should-not (memq #'tategaki-outline--after-change after-change-functions))
          (should-not (memq #'tategaki-outline--post-command post-command-hook)))
        (tategaki-pane-test--assert-source source state)))))

(ert-deftest tategaki-pane-comparison-close-restores-layout-and-both-copies ()
  (tategaki-pane-test--source
    (let ((old (generate-new-buffer " *pane old manuscript*"))
          (other (tategaki-pane-test--other-pane))
          (state (tategaki-pane-test--source-state source)))
      (with-current-buffer old (insert "第一章\n古い文章。\n"))
      (select-window (get-buffer-window source))
      (let* ((layout (mapcar #'window-buffer (window-list)))
             (copies (tategaki-diff-buffers old source)))
        (dolist (copy copies) (tategaki-pane-test--header-control copy))
        (tategaki-pane-test--click (get-buffer-window (cadr copies)))
        (should-not (cl-some #'buffer-live-p copies))
        (should (equal layout (mapcar #'window-buffer (window-list))))
        (should (get-buffer-window other))
        (tategaki-pane-test--assert-source source state)))))

(ert-deftest tategaki-pane-history-fallback-diff-has-working-close ()
  (tategaki-pane-test--source
    (let ((record (tategaki-history-snapshot 'manual source))
          (original-require (symbol-function 'require)))
      (cl-letf (((symbol-function 'require)
                 (lambda (feature &rest args)
                   (unless (eq feature 'tategaki-diff) (apply original-require feature args)))))
        (let ((panel (tategaki-history-diff record)))
          (should (bufferp panel))
          (tategaki-pane-test--click (get-buffer-window panel))
          (should (buffer-live-p panel)) (should-not (get-buffer-window panel)))))))

(ert-deftest tategaki-pane-settings-close-routes-to-unsaved-confirmation ()
  (tategaki-pane-test--source
    (let* ((state (tategaki-pane-test--source-state source))
           (settings (tategaki-settings source))
           (other (tategaki-pane-test--other-pane)))
      (with-current-buffer settings (tategaki-settings-set 'title "未保存の設定"))
      (select-window (get-buffer-window other))
      (tategaki-pane-test--click (get-buffer-window settings))
      (should (get-buffer-window settings)) (should (get-buffer-window other))
      (with-current-buffer settings
        (should tategaki-settings--closing)
        (should (string-match-p "変更を保存しますか" (buffer-string)))
        (tategaki-settings-discard))
      (should-not (buffer-live-p settings)) (should (get-buffer-window other))
      (tategaki-pane-test--assert-source source state))))

(ert-deftest tategaki-pane-export-status-log-directory-close-keep-running-process ()
  (tategaki-pane-test--source
    (let* ((state (tategaki-pane-test--source-state source))
           (log (generate-new-buffer " *pane running export log*"))
           (process (make-pipe-process :name "tategaki-pane-export-test" :buffer log :noquery t))
           (job (list :id "pane-test" :state 'running :source-hash "synthetic-hash"
                      :source-buffer source :directory directory :buffer (buffer-name log) :process process)))
      (puthash "pane-test" job tategaki-export--jobs)
      (tategaki-export-status "pane-test")
      (let ((status (current-buffer)))
        (tategaki-pane-test--header-control status)
        (dolist (label '("ログを表示" "出力フォルダー"))
          (pop-to-buffer status)
          (tategaki-pane-test--activate-button status label)
          (let ((panel (window-buffer (selected-window))))
            (tategaki-pane-test--header-control panel)
            (tategaki-pane-test--click (get-buffer-window panel))
            (should (buffer-live-p panel)) (should-not (get-buffer-window panel))
            (should (process-live-p process))))
        (pop-to-buffer status)
        (tategaki-pane-test--click (get-buffer-window status))
        (should (process-live-p process)) (should (buffer-live-p log)))
      (tategaki-pane-test--assert-source source state))))

(provide 'tategaki-pane-test)
;;; tategaki-pane-test.el ends here
