;;; tategaki-typeset-graphical-tests.el --- Rich editor GUI integration -*- lexical-binding: t; -*-
;; Run in a dedicated NS Emacs process.  Only Copilot transport is disabled;
;; rendering, native IME, Copilot overlays and the Corfu child frame are real.

(require 'ert)
(require 'cl-lib)
(require 'package)
(package-initialize)
(let* ((directory (file-name-directory (or load-file-name buffer-file-name)))
       (root (file-name-directory (directory-file-name directory))))
  (add-to-list 'load-path root))
(setq load-prefer-newer t)
(require 'tategaki)
(require 'copilot)
(require 'corfu)
(require 'isearch)
(require 'dom)
(require 'xml)

(defmacro tategaki-rich-gui--with-text (text &rest body)
  "Run BODY in an isolated, actually rendered rich source buffer."
  (declare (indent 1) (debug t))
  `(save-window-excursion
     (let ((source (generate-new-buffer " *Tategaki rich graphical test*"))
           (ns-working-overlay nil) (ns-working-text "") (mac-ime-hide-cursor nil)
           (copilot--overlay nil) (copilot--keymap-overlay nil)
           (corfu--preview-ov nil) (corfu--candidates nil) (corfu--base "")
           (corfu--index -1) (corfu--preselect -1) (corfu--frame nil)
           (corfu-auto nil) (corfu-preview-current t) (corfu-count 3))
       (unwind-protect
           (cl-letf (((symbol-function 'copilot--notify) #'ignore)
                     ((symbol-function 'copilot--async-request) #'ignore)
                     ((symbol-function 'copilot--cancel-completion) #'ignore))
             (switch-to-buffer source)
             (delete-other-windows)
             (text-mode)
             (insert ,text)
             (goto-char (point-min))
             (setq-local tategaki-typesetting t tategaki-column-height 6)
             (buffer-enable-undo)
             (setq buffer-undo-list nil)
             (set-buffer-modified-p nil)
             (tategaki-mode 1)
             (should (plist-get tategaki--layout :typeset))
             ,@body)
         (when (buffer-live-p source)
           (with-current-buffer source
             (ignore-errors (ns-delete-working-text))
             (ignore-errors (when completion-in-region-mode (corfu-quit)))
             (ignore-errors (corfu--preview-delete))
             (ignore-errors (tategaki-mode -1))
             (when (overlayp copilot--overlay) (delete-overlay copilot--overlay))
             (when (overlayp copilot--keymap-overlay) (delete-overlay copilot--keymap-overlay))
             (set-buffer-modified-p nil))
           (kill-buffer source))
         (when (frame-live-p corfu--frame) (delete-frame corfu--frame))))))

(defun tategaki-rich-gui--caret ()
  "Check actual cursor pixels and return its display string position."
  (tategaki-refresh)
  (redisplay t)
  (let* ((pixel (tategaki-position-pixel (point)))
         (cursor (window-cursor-info))
         (position (and pixel (posn-at-x-y (+ (plist-get pixel :x) 1)
                                          (+ (plist-get pixel :y) 1))))
         (object (and position (posn-string position))))
    (should pixel)
    (should cursor)
    (should object)
    (should (= (aref cursor 1) (plist-get pixel :x)))
    (should (= (aref cursor 2) (plist-get pixel :y)))
    (should (= (get-text-property (cdr object) 'tategaki-virtual-position (car object))
               tategaki--caret-position))
    object))

(defun tategaki-rich-gui--image-data (object)
  "Return the SVG payload at display OBJECT."
  (let* ((display (get-text-property (cdr object) 'display (car object)))
         (image (if (eq (car-safe display) 'image) display
                  (cl-find-if (lambda (item) (eq (car-safe item) 'image)) display))))
    (and image (plist-get (cdr image) :data))))

(ert-deftest tategaki-rich-gui-cursor-and-grouped-navigation ()
  (tategaki-rich-gui--with-text "前12👩‍👩‍👧‍👧後"
    (goto-char 2)
    (tategaki-rich-gui--caret)
    (tategaki-next-character)
    (should (= (point) 4))
    (tategaki-rich-gui--caret)
    (tategaki-next-character)
    (should (= (point) 11))
    (tategaki-rich-gui--caret)
    (tategaki-previous-character)
    (should (= (point) 4))
    (tategaki-previous-character)
    (should (= (point) 2))
    ;; A native source command may stop inside a composed grapheme.
    ;; The physical Up command must return to its real source start.
    (goto-char 8)
    (tategaki-rich-gui--caret)
    (tategaki-previous-character)
    (should (= (point) 4))
    (tategaki-rich-gui--caret)
    (should-not (buffer-modified-p))))

(ert-deftest tategaki-rich-gui-interior-source-positions-map-to-visible-cells ()
  (tategaki-rich-gui--with-text "前12が｜漢字《かんじ》後"
    (dolist (position '(2 3 4 5 6 7 8 10 12 13 15))
      (goto-char position)
      (let* ((object (tategaki-rich-gui--caret))
             (properties (text-properties-at (cdr object) (car object))))
        (should (= (plist-get properties 'tategaki-position) position))
        (should (tategaki-rich-gui--image-data object))))
    (should (equal (buffer-string) "前12が｜漢字《かんじ》後"))
    (should-not buffer-undo-list)))

(ert-deftest tategaki-rich-gui-real-isearch-is-visible-on-the-cursor-cell ()
  (tategaki-rich-gui--with-text "前12後"
    (let ((isearch-overlay nil) (isearch-face 'isearch)
          (search-highlight t) (isearch-regexp nil))
      (unwind-protect
          (progn
            (goto-char 2)
            (isearch-highlight 3 4)
            (let* ((object (tategaki-rich-gui--caret))
                   (face (get-text-property (cdr object) 'face (car object)))
                   (svg (tategaki-rich-gui--image-data object))
                   (background (tategaki-glyph--color (face-background 'isearch)
                                                      "#ffffff" (selected-frame))))
              (should (< (cl-position 'isearch face) (cl-position 'tategaki-cursor-face face)))
              (should (string-match-p (regexp-quote background) svg))))
        (isearch-dehighlight)))))

(ert-deftest tategaki-rich-gui-rotated-word-slices-retain-source-caret ()
  (tategaki-rich-gui--with-text "前Emacs後"
    (setq-local tategaki-typeset-latin-orientation 'rotate)
    (tategaki-refresh)
    (dolist (position '(2 3 5 6))
      (goto-char position)
      (let* ((object (tategaki-rich-gui--caret))
             (svg (tategaki-rich-gui--image-data object)))
        (should (string-match-p "rotate(90" svg))
        (should (= (get-text-property (cdr object) 'tategaki-position (car object))
                   position))))
    (goto-char 2)
    (tategaki-next-character)
    (should (= (point) 7))
    (tategaki-rich-gui--caret)
    (should (equal (buffer-string) "前Emacs後"))))

(ert-deftest tategaki-rich-gui-hanging-punctuation-has-a-visible-caret ()
  (dolist (mark '("、" "。" "，" "．"))
    (dolist (gap '(0 20))
      (tategaki-rich-gui--with-text (concat "漢字" mark "漢字")
        (setq-local tategaki-column-height 2 tategaki-character-spacing gap)
        (tategaki-refresh)
        (let* ((body (tategaki-rich-gui--image-data (tategaki-rich-gui--caret)))
               (normal-text
                (with-temp-buffer
                  (insert body)
                  (car (dom-by-tag (car (xml-parse-region (point-min) (point-max))) 'text)))))
          (goto-char 3)
          (should (plist-get (aref (tategaki--entry (point)) 4) :hanging))
          (let* ((object (tategaki-rich-gui--caret))
                 (svg (tategaki-rich-gui--image-data object))
                 (mark-text
                  (with-temp-buffer
                    (insert svg)
                    (car (dom-by-tag (car (xml-parse-region (point-min) (point-max))) 'text))))
                 (geometry (tategaki-typeset-view-geometry (selected-window) tategaki--metrics))
                 (expected-height (round (/ (float (plist-get geometry :row-height)) 2))))
            ;; Half-cell advance must not mean half-sized punctuation.
            (should (equal (dom-attr mark-text 'font-size) (dom-attr normal-text 'font-size)))
            (should (= (get-text-property (cdr object) 'tategaki-unit-height (car object))
                       expected-height))
            (should (> (plist-get (tategaki-position-pixel (point)) :height) 1))))
        (should (equal (buffer-string) (concat "漢字" mark "漢字")))
        (should-not (buffer-modified-p))))))

(ert-deftest tategaki-rich-gui-fixed-pages-spread-grid-and-navigation ()
  (tategaki-rich-gui--with-text (make-string 1300 ?字)
    (dolist (spec '(("20x20" 20 20 401) ("40x30" 40 30 1201)))
      (goto-char (point-min))
      (tategaki-manuscript-set-preset (nth 0 spec))
      (setq-local tategaki-manuscript-grid t tategaki-manuscript-spread nil)
      (tategaki-refresh)
      (should (= (plist-get tategaki--layout :height) (nth 1 spec)))
      (should (= tategaki--page-size (nth 2 spec)))
      (let* ((object (tategaki-rich-gui--caret))
             (svg (tategaki-rich-gui--image-data object)))
        (should (string-match-p "stroke=" svg)))
      ;; A whole paper must actually fit.  Image and spacer baselines may
      ;; otherwise enlarge each physical scanline despite correct geometry.
      (let* ((geometry (tategaki-typeset-view-geometry (selected-window)
                                                     tategaki--metrics))
             (pitch (plist-get geometry :row-pitch))
             (top (plist-get (tategaki-position-pixel 1) :y)))
        (dolist (row (list 2 (nth 1 spec)))
          (goto-char row)
          (tategaki-rich-gui--caret)
          (let ((pixel (tategaki-position-pixel (point))))
            (should (= (plist-get pixel :y) (+ top (* (1- row) pitch))))
            (should (<= (+ (plist-get pixel :y) (plist-get pixel :height))
                        (window-body-height nil t))))))
      (tategaki-goto-page 2)
      (should (= (point) (nth 3 spec)))
      (should (= (plist-get (tategaki-manuscript-page-info tategaki--layout (point)) :current) 2))
      (tategaki-rich-gui--caret)
      (tategaki-manuscript-toggle-spread)
      (should (= tategaki--page-size (* 2 (nth 2 spec))))
      (tategaki-rich-gui--caret))
    (should-not (buffer-modified-p))))

(ert-deftest tategaki-rich-gui-native-ime-preview-wraps-without-source-edit ()
  (tategaki-rich-gui--with-text "前後"
    (setq-local tategaki-column-height 3)
    (goto-char 2)
    (setq ns-working-text "日本語入力")
    (let (coordinates)
      (dotimes (index (length ns-working-text))
        (ns-put-marked-text (list 'ns-put-marked-text index 1))
        (let* ((object (tategaki-rich-gui--caret))
               (properties (text-properties-at (cdr object) (car object)))
               (pixel (tategaki-position-pixel (point))))
          (should (= (plist-get properties 'tategaki-preedit-index) index))
          (should (memq 'ns-marked-text-face (plist-get properties 'face)))
          (push (cons (plist-get pixel :x) (plist-get pixel :y)) coordinates)))
      (setq coordinates (nreverse coordinates))
      (should (= (caar coordinates) (caadr coordinates)))
      (should (< (cdar coordinates) (cdadr coordinates)))
      (should (< (car (nth 2 coordinates)) (caar coordinates))))
    (should (equal (buffer-string) "前後"))
    (should-not (buffer-modified-p))
    (should-not buffer-undo-list)))

(ert-deftest tategaki-rich-gui-real-copilot-preview-and-native-accept-undo ()
  (tategaki-rich-gui--with-text "前後"
    (goto-char 2)
    (copilot--display-overlay-completion "12日本語" nil "12日本語" 2 2)
    (let* ((object (tategaki-rich-gui--caret))
           (face (get-text-property (cdr object) 'face (car object))))
      (should (eq tategaki--preview-kind 'copilot))
      (should (memq 'copilot-overlay-face face)))
    (should (equal (buffer-string) "前後"))
    (should-not buffer-undo-list)
    (copilot-accept-completion)
    (tategaki-refresh)
    (should (equal (buffer-string) "前12日本語後"))
    (undo-boundary)
    (undo-only 1)
    (tategaki-refresh)
    (should (equal (buffer-string) "前後"))))

(ert-deftest tategaki-rich-gui-real-corfu-popup-tracks-composed-caret ()
  (tategaki-rich-gui--with-text "前日本後"
    (goto-char 4)
    (corfu-mode 1)
    (setq corfu--candidates '("日本語入力候補") corfu--index 0)
    (corfu--preview-current 2 4)
    (tategaki-rich-gui--caret)
    (corfu--popup-show (posn-at-point) 7 12 '("日本語入力候補" "日本語入力確認") 0)
    (redisplay t)
    (let* ((pixel (tategaki-position-pixel (point)))
           (geometry (frame-parameter corfu--frame 'corfu--geometry))
           (edges (window-inside-pixel-edges)))
      (should (frame-live-p corfu--frame))
      (should (frame-visible-p corfu--frame))
      (should (= (cadr geometry)
                 (+ (cadr edges) (plist-get pixel :y)
                    (max (default-line-height) (plist-get pixel :height)))))
      ;; Corfu aligns the candidate text, not its left fringe, to point.
      ;; At the right edge it instead keeps the entire child frame visible.
      (with-current-buffer (window-buffer (frame-root-window corfu--frame))
        (let* ((cw (default-font-width))
               (left (min 16 (ceiling (* cw corfu-left-margin-width))))
               (right (min 16 (ceiling (* cw corfu-right-margin-width))))
               (text-x (+ (car geometry) left corfu-border-width))
               (right-edge (+ (car geometry) (nth 2 geometry) left right
                              (* 2 corfu-border-width))))
          (should (or (= text-x (+ (car edges) (plist-get pixel :x)))
                      (= right-edge (frame-pixel-width
                                     (frame-parent corfu--frame))))))))
    (should (equal (buffer-string) "前日本後"))
    (should-not (buffer-modified-p))))

(run-at-time 120 nil (lambda () (kill-emacs 2)))
(run-at-time
 1 nil
 (lambda ()
   (let ((status 2))
     (condition-case err
         (progn
           (unless (and (display-graphic-p) (featurep 'ns))
             (error "Rich integration requires dedicated NS Emacs"))
           (set-frame-parameter nil 'name "TATEGAKI RICH INTEGRATION")
           (delete-other-windows)
           (set-frame-size nil 100 40)
           (let ((stats (ert-run-tests-batch "^tategaki-rich-gui-")))
             (setq status (if (and (= (ert-stats-completed-expected stats) 9)
                                  (zerop (ert-stats-completed-unexpected stats))
                                  (zerop (ert-stats-skipped stats))) 0 1))))
       (error (message "Rich GUI setup failure: %S" err)))
     (with-current-buffer "*Messages*"
       (write-region (point-min) (point-max)
                     (expand-file-name "tategaki-typeset-gui-tests.log" temporary-file-directory)))
     (kill-emacs status))))

;;; tategaki-typeset-graphical-tests.el ends here
