;;; tategaki-ai-test.el --- Privacy and source-grounding regressions -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'ert)
(require 'cl-lib)
(require 'tategaki-studio)
(require 'tategaki-assistant)

(defmacro tategaki-ai-test--source (&rest body)
  (declare (indent 0))
  `(save-window-excursion
     (let ((source (generate-new-buffer " ai-test.txt"))
           (directory (make-temp-file "tategaki-ai-test-" t)))
       (unwind-protect
           (with-current-buffer source
             (text-mode)
             (setq default-directory (file-name-as-directory directory))
             (setq-local tategaki-ai-enabled t tategaki-ai-model "test"
                         tategaki-ai-endpoint "http://localhost:12345/v1")
             (insert "第1章\n母を待っていた。\n\n第2章\n花子は鍵を見つけた。\n\n第3章\n未来の秘密が明かされる。")
             (goto-char 10)
             (set-buffer-modified-p nil)
             (buffer-enable-undo)
             (setq buffer-undo-list nil)
             (switch-to-buffer source)
             ,@body)
         (when (buffer-live-p source)
           (with-current-buffer source
             (when (buffer-live-p tategaki-assistant--buffer)
               (kill-buffer tategaki-assistant--buffer))
             (set-buffer-modified-p nil))
           (kill-buffer source))
         (delete-directory directory t)))))

(ert-deftest tategaki-ai-private-by-default ()
  (let ((tategaki-ai-enabled nil) (tategaki-ai-model "test"))
    (should-error (tategaki-ai-authorize) :type 'user-error))
  (dolist (url '("http://localhost:11434/v1" "http://127.0.0.1:8080/v1" "http://[::1]:8080/v1"))
    (should (tategaki-ai-local-p url)))
  (dolist (url '("http://localhost.example.com/v1" "http://127.0.0.1@evil.example/v1"
                 "file:///tmp/llm" "https://example.com/v1"))
    (should-not (tategaki-ai-local-p url)))
  (let ((tategaki-ai-enabled t) (tategaki-ai-model "test")
        (tategaki-ai-endpoint "https://remote.example/v1") (tategaki-ai-allow-remote nil))
    (should-error (tategaki-ai-authorize) :type 'user-error)))

(ert-deftest tategaki-ai-transport-no-redirect-and-errors-once ()
  (let ((response (generate-new-buffer " *ai response*")) cb delivered)
    (unwind-protect
        (cl-letf (((symbol-function 'url-retrieve)
                   (lambda (_url callback &rest _)
                     (should (= url-max-redirections 0))
                     (setq cb callback) response)))
          (tategaki-ai--request "/models" nil (lambda (r) (push r delivered)) "GET")
          (with-current-buffer response
            (setq-local url-http-response-status 302)
            (funcall cb nil))
          (should (= (length delivered) 1))
          (should-not (plist-get (car delivered) :ok)))
      (when (buffer-live-p response) (kill-buffer response)))))

(ert-deftest tategaki-ai-chat-response-validation ()
  (let (result)
    (cl-letf (((symbol-function 'tategaki-ai--request)
               (lambda (_ payload callback &rest _)
                 (should (eq (alist-get 'stream payload) :json-false))
                 (funcall callback '(:ok t :data ((choices . (((message . ((content . "回答"))))))))))))
      (tategaki-ai-chat '(((role . "user") (content . "相談"))) (lambda (r) (setq result r)) t)
      (should (equal (plist-get result :text) "回答")))
  (cl-letf (((symbol-function 'tategaki-ai--request)
             (lambda (_ _payload callback &rest _) (funcall callback '(:ok t :data nil)))))
    (tategaki-ai-chat nil (lambda (r) (should-not (plist-get r :ok))) t))))

(ert-deftest tategaki-semantic-chunks-preserve-source-and-cutoff ()
  (tategaki-ai-test--source
    (let ((text (buffer-string)) (undo buffer-undo-list) (pos (point))
          (tategaki-semantic-chunk-size 50))
      (let ((chunks (tategaki-semantic-chunks nil 25)))
        (should chunks)
        (dolist (chunk chunks)
          (should (<= (plist-get chunk :end) 25))
          (should (equal (plist-get chunk :text)
                         (buffer-substring-no-properties (plist-get chunk :start) (plist-get chunk :end)))))
        (should-not (string-match-p "未来" (mapconcat (lambda (c) (plist-get c :text)) chunks ""))))
      (should (equal text (buffer-string)))
      (should (eq undo buffer-undo-list))
      (should (= pos (point)))
      (should-not (buffer-modified-p)))))

(ert-deftest tategaki-semantic-offline-japanese-search-and-stale-jump ()
  (tategaki-ai-test--source
    (let ((matches (tategaki-semantic-lexical-search "花子が鍵を見つけた場面" (tategaki-semantic-chunks))))
      (should (string-match-p "鍵" (plist-get (car matches) :text)))
      (insert "変更")
      (should-error (tategaki-semantic-visit (car matches)) :type 'user-error))))

(ert-deftest tategaki-semantic-cosine-dimensions-and-zero ()
  (should (= (tategaki-semantic-cosine '(1 0) '(1 0)) 1.0))
  (should (= (tategaki-semantic-cosine '(0 0) '(1 0)) 0.0))
  (should (= (tategaki-semantic-cosine '(1 0) '(1)) -1.0)))

(ert-deftest tategaki-semantic-index-discard-after-edit ()
  (tategaki-ai-test--source
    (let (pending outcome)
      (cl-letf (((symbol-function 'tategaki-ai-embed)
                 (lambda (_ cb &optional _) (setq pending cb))))
        (tategaki-semantic-index (lambda (r) (setq outcome r)))
        (insert "索引中の編集")
        (funcall pending '(:ok t :vectors ((1 0) (0 1) (1 1))))
        (sleep-for 0.01)
        (should-not (plist-get outcome :ok))
        (should-not tategaki-semantic--index)))))

(ert-deftest tategaki-semantic-index-persistence-rejects-stale-and-malformed ()
  (tategaki-ai-test--source
    (setq buffer-file-name (expand-file-name "novel.txt" directory))
    (setq tategaki-semantic--index
          (list :hash (tategaki-semantic-hash) :model (tategaki-semantic--model-key)
                :chunks (mapcar (lambda (c) (plist-put c :vector '(1.0 0.5)))
                                (tategaki-semantic-chunks))))
    (tategaki-semantic-save-index)
    (setq tategaki-semantic--index nil)
    (tategaki-semantic-load-index)
    (should tategaki-semantic--index)
    (setq tategaki-semantic--index nil)
    (insert "変更")
    (tategaki-semantic-load-index)
    (should-not tategaki-semantic--index)
    (with-temp-file (tategaki-semantic--cache-file) (insert "{broken"))
    (tategaki-semantic-load-index)
    (should-not tategaki-semantic--index)))

(ert-deftest tategaki-rag-resource-provenance-and-no-future-context ()
  (tategaki-ai-test--source
    (make-directory (expand-file-name ".tategaki/resources/" directory) t)
    (with-temp-file (expand-file-name ".tategaki/resources/notes.txt" directory) (insert "母の鍵は資料にある。"))
    (let (result)
      (tategaki-rag-context "母の鍵" (lambda (r) (setq result r)))
      (should (seq-some (lambda (c) (eq (plist-get c :kind) 'resource)) (plist-get result :chunks)))
      (should (string-match-p "\\[資料:notes.txt:" (plist-get result :text)))
      (tategaki-rag-context "未来の秘密" (lambda (r) (setq result r)) 15)
      (should-not (string-match-p "未来\\|資料" (plist-get result :text)))
      (should (cl-every (lambda (c) (<= (plist-get c :end) 15)) (plist-get result :chunks))))))

(ert-deftest tategaki-assistant-citations-and-text-undo-invariance ()
  (tategaki-ai-test--source
    (let ((text (buffer-string)) (undo buffer-undo-list) pending answer-buffer)
      (cl-letf (((symbol-function 'tategaki-ai-chat)
                 (lambda (messages cb &optional _)
                   (should (string-match-p "原稿を自動" (alist-get 'content (car messages))))
                   (setq pending cb))))
        (tategaki-ask "母を待つ場面について")
        (setq answer-buffer (current-buffer))
        (funcall pending '(:ok t :text "原稿から確認できること\n母を待っている。[第1章:1]\n不明な参照 [架空:9999]"))
        (with-current-buffer answer-buffer
          (goto-char (point-min))
          (search-forward "[第1章:1]")
          (should (button-at (1- (point))))
          (search-forward "[架空:9999]")
          (should-not (button-at (1- (point)))))
      (with-current-buffer source
        (should (equal text (buffer-string)))
        (should (eq undo buffer-undo-list))
        (should-not (buffer-modified-p)))))))

(ert-deftest tategaki-assistant-stale-response-disables-citations ()
  (tategaki-ai-test--source
    (let (pending answer-buffer)
      (cl-letf (((symbol-function 'tategaki-ai-chat)
                 (lambda (_ cb &optional _) (setq pending cb))))
        (tategaki-ask "母について")
        (setq answer-buffer (current-buffer))
        (with-current-buffer source (insert "変更"))
        (funcall pending '(:ok t :text "回答 [第1章:1]"))
        (with-current-buffer answer-buffer
          (goto-char (point-min))
          (should (search-forward "参照移動は無効" nil t))
          (search-forward "[第1章:1]")
          (should-not (button-at (1- (point)))))))))

(provide 'tategaki-ai-test)
