;;; tategaki-layout-test.el --- Literal vertical layout tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'tategaki-layout)

(defun tategaki-layout-test--check-positions (text height &optional width start)
  "Check every insertion position of TEXT at HEIGHT and WIDTH, from START."
  (let* ((layout (tategaki-layout-render text height width start))
         (display (plist-get layout :text))
         (positions (plist-get layout :positions))
         offsets coordinates)
    (should (= (length positions) (1+ (length text))))
    (dotimes (index (length positions))
      (let* ((entry (aref positions index))
             (position (+ (or start 1) index))
             (offset (aref entry 1)))
        (should (= (aref entry 0) position))
        (should (= (get-text-property offset 'tategaki-position display) position))
        (should (= (get-text-property offset 'tategaki-row display) (aref entry 2)))
        (should (= (get-text-property offset 'tategaki-column display) (aref entry 3)))
        (should (< (aref entry 2) height))
        (push offset offsets)
        (push (cons (aref entry 2) (aref entry 3)) coordinates)))
    (should (= (length positions) (length (delete-dups offsets))))
    (should (= (length positions) (length (delete-dups coordinates))))
    layout))

(ert-deftest tategaki-layout-empty-buffer-has-eof-cell ()
  (let ((layout (tategaki-layout-test--check-positions "" 2)))
    (should (= (plist-get layout :columns) 1))
    (should (equal (aref (plist-get layout :positions) 0) [1 0 0 0]))
    (should (string-prefix-p tategaki-layout-eof-symbol (plist-get layout :text)))))

(ert-deftest tategaki-layout-wraps-down-then-left ()
  (let* ((layout (tategaki-layout-test--check-positions "日本語abc" 3))
         (positions (plist-get layout :positions)))
    (should (= (plist-get layout :columns) 3))
    (should (equal (mapcar (lambda (entry) (cons (aref entry 2) (aref entry 3)))
                          positions)
                   '((0 . 0) (1 . 0) (2 . 0) (0 . 1) (1 . 1) (2 . 1) (0 . 2))))
    (should (< (aref (aref positions 3) 1) (aref (aref positions 0) 1)))))

(ert-deftest tategaki-layout-preserves-newlines-and-empty-lines ()
  (let* ((layout (tategaki-layout-test--check-positions "A\n\nB\n" 5))
         (positions (plist-get layout :positions)))
    (should (= (plist-get layout :columns) 4))
    (should (equal (mapcar (lambda (entry) (cons (aref entry 2) (aref entry 3)))
                          positions)
                   '((0 . 0) (1 . 0) (0 . 1) (0 . 2) (1 . 2) (0 . 3))))))

(ert-deftest tategaki-layout-newline-after-full-column-is-addressable ()
  (let* ((layout (tategaki-layout-test--check-positions "AB\nC" 2))
         (positions (plist-get layout :positions)))
    (should (equal (mapcar (lambda (entry) (cons (aref entry 2) (aref entry 3)))
                          positions)
                   '((0 . 0) (1 . 0) (0 . 1) (0 . 2) (1 . 2))))))

(ert-deftest tategaki-layout-keeps-spaces-tabs-cr-and-combining-positions ()
  (tategaki-layout-test--check-positions " \t\r\nあ　é\0\177\u200d " 4)
  (tategaki-layout-test--check-positions "\n\n\t \n" 1))

(ert-deftest tategaki-layout-does-not-mutate-or-inherit-source-properties ()
  (let* ((text (propertize "* 見出し\t\n\n末尾  " 'display "CHANGED" 'face 'bold))
         (before (copy-sequence text))
         (layout (tategaki-layout-test--check-positions text 7)))
    (should (equal-including-properties text before))
    (should-not (text-property-any 0 (length (plist-get layout :text))
                                   'display "CHANGED" (plist-get layout :text)))))

(ert-deftest tategaki-layout-narrowed-position-start ()
  (let ((layout (tategaki-layout-test--check-positions "本文\n" 5 nil 42)))
    (should (= (aref (aref (plist-get layout :positions) 0) 0) 42))
    (should (= (aref (aref (plist-get layout :positions) 3) 0) 45))))

(ert-deftest tategaki-layout-right-aligns-without-truncating ()
  (let ((wide (tategaki-layout-test--check-positions "AB" 2 12))
        (narrow (tategaki-layout-test--check-positions "ABCD" 2 1)))
    (should (= (plist-get wide :padding) 8))
    (dolist (line (split-string (plist-get wide :text) "\n"))
      (should (= (string-width line) 12)))
    (should (= (plist-get narrow :padding) 0))
    (dolist (line (split-string (plist-get narrow :text) "\n"))
      (should (= (string-width line) 6)))))

(ert-deftest tategaki-layout-punctuation-conversion-is-display-only ()
  (let* ((text "「あ」。")
         (tategaki-layout-use-vertical-forms t)
         (layout (tategaki-layout-test--check-positions text 6)))
    (should (string-prefix-p "﹁" (plist-get layout :text)))
    (should (equal text "「あ」。"))
    (let ((tategaki-layout-use-vertical-forms nil))
      (should (string-prefix-p "「" (plist-get (tategaki-layout-render text 6) :text))))))

(ert-deftest tategaki-layout-markers-are-configurable-and-faced ()
  (let* ((tategaki-layout-newline-symbol "N")
         (tategaki-layout-tab-symbol "T")
         (tategaki-layout-eof-symbol "E")
         (layout (tategaki-layout-test--check-positions "\t\n" 4))
         (display (plist-get layout :text))
         (positions (plist-get layout :positions)))
    (dotimes (index 3)
      (let ((offset (aref (aref positions index) 1)))
        (should (= (aref display offset) (aref "TNE" index)))
        (should (eq (get-text-property offset 'face display)
                    'tategaki-layout-control-face))))))

(ert-deftest tategaki-layout-invalid-markers-do-not-break-grid ()
  (let ((tategaki-layout-newline-symbol "\n")
        (tategaki-layout-tab-symbol "TOO WIDE")
        (tategaki-layout-eof-symbol ""))
    (let ((layout (tategaki-layout-test--check-positions "\t\n" 3)))
      (should (= (length (split-string (plist-get layout :text) "\n")) 3)))))

(ert-deftest tategaki-layout-multi-character-markers-use-fallback ()
  (let* ((tategaki-layout-tab-symbol "TT")
         (layout (tategaki-layout-test--check-positions "\t" 3))
         (display (plist-get layout :text))
         (tab-entry (aref (plist-get layout :positions) 0)))
    (should (= (aref display (aref tab-entry 1)) ?⇥))))

(ert-deftest tategaki-layout-validates-dimensions ()
  (dolist (height '(0 -1 1.5 nil))
    (should-error (tategaki-layout-render "text" height) :type 'wrong-type-argument))
  (should-error (tategaki-layout-render "text" 3 -1) :type 'wrong-type-argument)
  (should-error (tategaki-layout-render "text" 3 nil 0) :type 'wrong-type-argument))

(provide 'tategaki-layout-test)
;;; tategaki-layout-test.el ends here
