;;; tategaki-typeset-graphical-tests.el --- Rich editor GUI integration -*- lexical-binding: t; -*-

;; Copyright (C) 2026 seijiro and contributors.
;; SPDX-License-Identifier: GPL-3.0-or-later
;;
;; This file is part of my-tategaki.
;;
;; my-tategaki is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.
;;
;; my-tategaki is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with my-tategaki.  If not, see <https://www.gnu.org/licenses/>.

;; Run in a dedicated NS Emacs process.  Only Copilot transport is disabled;
;; rendering, native IME, Copilot overlays and the Corfu child frame are real.

(require 'ert)
(require 'cl-lib)
(require 'package)
(package-initialize)
(let* ((directory (file-name-directory (or load-file-name buffer-file-name)))
       (root (file-name-directory (directory-file-name directory))))
  (add-to-list 'load-path root))
(setq load-prefer-newer t)
(require 'tategaki)
(require 'copilot)
(require 'corfu)
(require 'isearch)
(require 'dom)
(require 'xml)
(require 'server)
(defvar tategaki-rich-gui--directory (make-temp-file "/tmp/tategaki-rich-gui-" t))
(setq server-name "tategaki-isolated-rich-gui"
      server-socket-dir (expand-file-name "sockets" tategaki-rich-gui--directory))
(make-directory server-socket-dir t)
(set-file-modes server-socket-dir #o700)
(server-start)
(add-hook 'kill-emacs-hook
          (lambda () (ignore-errors (delete-directory tategaki-rich-gui--directory t))) t)

(defmacro tategaki-rich-gui--with-text (text &rest body)
  "Run BODY in an isolated, actually rendered rich source buffer."
  (declare (indent 1) (debug t))
  `(save-window-excursion
     (let ((source (generate-new-buffer " *Tategaki rich graphical test*"))
           (ns-working-overlay nil) (ns-working-text "") (mac-ime-hide-cursor nil)
           (copilot--overlay nil) (copilot--keymap-overlay nil)
           (corfu--preview-ov nil) (corfu--candidates nil) (corfu--base "")
           (corfu--index -1) (corfu--preselect -1) (corfu--frame nil)
           (corfu-auto nil) (corfu-preview-current t) (corfu-count 3))
       (unwind-protect
           (cl-letf (((symbol-function 'copilot--notify) #'ignore)
                     ((symbol-function 'copilot--async-request) #'ignore)
                     ((symbol-function 'copilot--cancel-completion) #'ignore))
             (switch-to-buffer source)
             (delete-other-windows)
             (text-mode)
             (insert ,text)
             (goto-char (point-min))
             (setq-local tategaki-typesetting t tategaki-column-height 6)
             (buffer-enable-undo)
             (setq buffer-undo-list nil)
             (set-buffer-modified-p nil)
             (tategaki-mode 1)
             (should (plist-get tategaki--layout :typeset))
             ,@body)
         (when (buffer-live-p source)
           (with-current-buffer source
             (ignore-errors (ns-delete-working-text))
             (ignore-errors (when completion-in-region-mode (corfu-quit)))
             (ignore-errors (corfu--preview-delete))
             (ignore-errors (tategaki-mode -1))
             (when (overlayp copilot--overlay) (delete-overlay copilot--overlay))
             (when (overlayp copilot--keymap-overlay) (delete-overlay copilot--keymap-overlay))
             (set-buffer-modified-p nil))
           (kill-buffer source))
         (when (frame-live-p corfu--frame) (delete-frame corfu--frame))))))

(defun tategaki-rich-gui--caret ()
  "Check actual cursor pixels and return its display string position."
  (tategaki-refresh)
  (redisplay t)
  (let* ((pixel (tategaki-position-pixel (point)))
         (cursor (window-cursor-info))
         (top (+ (window-header-line-height) (window-tab-line-height)))
         (position (and pixel (posn-at-x-y (+ (plist-get pixel :x) 1)
                                          (+ top (plist-get pixel :y) 1))))
         (object (and position (posn-string position))))
    (should pixel)
    (should cursor)
    (should object)
    (should (= (aref cursor 1) (plist-get pixel :x)))
    ;; Both native cursor and posn-at-x-y input include header/tab lines.
    ;; The posn-x-y result and our public pixel API exclude them, as Corfu
    ;; expects.  posn-at-x-y and posn-x-y are not inverses in such windows.
    (should (= (aref cursor 2) (+ top (plist-get pixel :y))))
    (should (= (get-text-property (cdr object) 'tategaki-virtual-position (car object))
               tategaki--caret-position))
    object))

(defun tategaki-rich-gui--image-data (object)
  "Return the SVG payload at display OBJECT."
  (let* ((display (get-text-property (cdr object) 'display (car object)))
         (image (if (eq (car-safe display) 'image) display
                  (cl-find-if (lambda (item) (eq (car-safe item) 'image)) display))))
    (and image (plist-get (cdr image) :data))))

(ert-deftest tategaki-rich-gui-cursor-and-grouped-navigation ()
  (tategaki-rich-gui--with-text "前12👩‍👩‍👧‍👧後"
    (goto-char 2)
    (tategaki-rich-gui--caret)
    (tategaki-next-character)
    (should (= (point) 4))
    (tategaki-rich-gui--caret)
    (tategaki-next-character)
    (should (= (point) 11))
    (tategaki-rich-gui--caret)
    (tategaki-previous-character)
    (should (= (point) 4))
    (tategaki-previous-character)
    (should (= (point) 2))
    ;; A native source command may stop inside a composed grapheme.
    ;; The physical Up command must return to its real source start.
    (goto-char 8)
    (tategaki-rich-gui--caret)
    (tategaki-previous-character)
    (should (= (point) 4))
    (tategaki-rich-gui--caret)
    (should-not (buffer-modified-p))))

(ert-deftest tategaki-rich-gui-interior-source-positions-map-to-visible-cells ()
  (tategaki-rich-gui--with-text "前12が｜漢字《かんじ》後"
    (dolist (position '(2 3 4 5 6 7 8 10 12 13 15))
      (goto-char position)
      (let* ((object (tategaki-rich-gui--caret))
             (properties (text-properties-at (cdr object) (car object))))
        (should (= (plist-get properties 'tategaki-position) position))
        (should (tategaki-rich-gui--image-data object))))
    (should (equal (buffer-string) "前12が｜漢字《かんじ》後"))
    (should-not buffer-undo-list)))

(ert-deftest tategaki-rich-gui-real-isearch-is-visible-on-the-cursor-cell ()
  (tategaki-rich-gui--with-text "前12後"
    (let ((isearch-overlay nil) (isearch-face 'isearch)
          (search-highlight t) (isearch-regexp nil))
      (unwind-protect
          (progn
            (goto-char 2)
            (isearch-highlight 3 4)
            (let* ((object (tategaki-rich-gui--caret))
                   (face (get-text-property (cdr object) 'face (car object)))
                   (svg (tategaki-rich-gui--image-data object))
                   (background (tategaki-glyph--color (face-background 'isearch)
                                                      "#ffffff" (selected-frame))))
              (should (< (cl-position 'isearch face) (cl-position 'tategaki-cursor-face face)))
              (should (string-match-p (regexp-quote background) svg))))
        (isearch-dehighlight)))))

(ert-deftest tategaki-rich-gui-rotated-word-slices-retain-source-caret ()
  (tategaki-rich-gui--with-text "前Emacs後"
    (setq-local tategaki-typeset-latin-orientation 'rotate)
    (tategaki-refresh)
    (dolist (position '(2 3 5 6))
      (goto-char position)
      (let* ((object (tategaki-rich-gui--caret))
             (svg (tategaki-rich-gui--image-data object)))
        (should (string-match-p "rotate(90" svg))
        (should (= (get-text-property (cdr object) 'tategaki-position (car object))
                   position))))
    (goto-char 2)
    (tategaki-next-character)
    (should (= (point) 7))
    (tategaki-rich-gui--caret)
    (should (equal (buffer-string) "前Emacs後"))))

(ert-deftest tategaki-rich-gui-hanging-punctuation-has-a-visible-caret ()
  (dolist (mark '("、" "。" "，" "．"))
    (dolist (gap '(0 20))
      (tategaki-rich-gui--with-text (concat "漢字" mark "漢字")
        (setq-local tategaki-column-height 2 tategaki-character-spacing gap)
        (tategaki-refresh)
        (let* ((body (tategaki-rich-gui--image-data (tategaki-rich-gui--caret)))
               (normal-text
                (with-temp-buffer
                  (insert body)
                  (car (dom-by-tag (car (xml-parse-region (point-min) (point-max))) 'text)))))
          (goto-char 3)
          (should (plist-get (aref (tategaki--entry (point)) 4) :hanging))
          (let* ((object (tategaki-rich-gui--caret))
                 (svg (tategaki-rich-gui--image-data object))
                 (mark-text
                  (with-temp-buffer
                    (insert svg)
                    (car (dom-by-tag (car (xml-parse-region (point-min) (point-max))) 'text))))
                 (geometry (tategaki-typeset-view-geometry (selected-window) tategaki--metrics))
                 (expected-height (round (/ (float (plist-get geometry :row-height)) 2))))
            ;; Half-cell advance must not mean half-sized punctuation.
            (should (equal (dom-attr mark-text 'font-size) (dom-attr normal-text 'font-size)))
            (should (= (get-text-property (cdr object) 'tategaki-unit-height (car object))
                       expected-height))
            (should (> (plist-get (tategaki-position-pixel (point)) :height) 1))))
        (should (equal (buffer-string) (concat "漢字" mark "漢字")))
        (should-not (buffer-modified-p))))))

(ert-deftest tategaki-rich-gui-fixed-pages-spread-grid-and-navigation ()
  (tategaki-rich-gui--with-text (make-string 1300 ?字)
    (setq-local tategaki-manuscript-fit-window t)
    (dolist (spec '(("20x20" 20 20 401) ("40x30" 40 30 1201)))
      (goto-char (point-min))
      (tategaki-manuscript-set-preset (nth 0 spec))
      (setq-local tategaki-manuscript-grid t tategaki-manuscript-spread nil)
      (tategaki-refresh)
      (should (= (plist-get tategaki--layout :height) (nth 1 spec)))
      (should (= tategaki--page-size (nth 2 spec)))
      (let* ((object (tategaki-rich-gui--caret))
             (svg (tategaki-rich-gui--image-data object)))
        (should (string-match-p "stroke=" svg)))
      ;; A whole paper must actually fit.  Image and spacer baselines may
      ;; otherwise enlarge each physical scanline despite correct geometry.
      (let* ((geometry (tategaki-typeset-view-geometry (selected-window)
                                                     tategaki--metrics))
             (pitch (plist-get geometry :row-pitch))
             (top (plist-get (tategaki-position-pixel 1) :y)))
        (dolist (row (list 2 (nth 1 spec)))
          (goto-char row)
          (tategaki-rich-gui--caret)
          (let ((pixel (tategaki-position-pixel (point))))
            (should (= (plist-get pixel :y) (+ top (* (1- row) pitch))))
            (should (<= (+ (plist-get pixel :y) (plist-get pixel :height))
                        (window-body-height nil t))))))
      (tategaki-goto-page 2)
      (should (= (point) (nth 3 spec)))
      (should (= (plist-get (tategaki-manuscript-page-info tategaki--layout (point)) :current) 2))
      (tategaki-rich-gui--caret)
      (tategaki-manuscript-toggle-spread)
      (should (= tategaki--page-size (* 2 (nth 2 spec))))
      (tategaki-rich-gui--caret))
    (should-not (buffer-modified-p))))

(ert-deftest tategaki-rich-gui-paper-zoom-preserves-size-with-partial-viewport ()
  (let ((width (frame-width)) (height (frame-height)))
    (unwind-protect
        (progn
          (set-frame-size nil 80 40)
          (tategaki-rich-gui--with-text (make-string 1700 ?字)
            (setq-local tategaki-manuscript-size '(20 . 20)
                        tategaki-manuscript-spread t tategaki-manuscript-grid t
                        tategaki-manuscript-fit-window nil)
            (let ((text (buffer-string)) (undo buffer-undo-list)
                  (tick (buffer-chars-modified-tick)) small large fonts)
              (dolist (amount '(-3 0))
                (tategaki-text-scale-reset)
                (tategaki-text-scale-increase amount)
                (goto-char 1)
                (let* ((object (tategaki-rich-gui--caret))
                       (svg (tategaki-rich-gui--image-data object))
                       (geometry (tategaki-typeset-view-geometry (selected-window) tategaki--metrics))
                       (font-size
                        (with-temp-buffer
                          (insert svg)
                          (string-to-number
                           (dom-attr (car (dom-by-tag (car (xml-parse-region (point-min) (point-max)))
                                                     'text)) 'font-size)))))
                  (if (= amount -3) (setq small geometry) (setq large geometry))
                  (push font-size fonts)
                  (should (string-match-p "stroke=" svg))
                  (should (= (plist-get tategaki--layout :height) 20))
                  (should (= (tategaki-manuscript--columns-per-page) 20))))
              (should (> (plist-get large :body) (plist-get small :body)))
              (should (> (car fonts) (cadr fonts)))
              (should (< (plist-get large :capacity) (plist-get small :capacity)))
              (should (< (plist-get large :capacity) 40))
              (message "Partial paper zoom -3→0: body %s→%s, SVG font %s→%s, columns %s→%s"
                       (plist-get small :body) (plist-get large :body) (cadr fonts) (car fonts)
                       (plist-get small :capacity) (plist-get large :capacity))
              ;; Begin inside a sheet, so the paper gap must follow absolute
              ;; columns 19/20 and 39/40, not the viewport's own midpoint.
              (dolist (first '(17 37))
                (tategaki-scroll-to-column first)
                (tategaki-rich-gui--caret)
                (should (= tategaki--page first))
                (let* ((boundary (* 20 (1+ (/ first 20))))
                       (before (tategaki-position-pixel (1+ (* 20 (1- boundary)))))
                       (after (tategaki-position-pixel (1+ (* 20 boundary))))
                       (same (tategaki-position-pixel (1+ (* 20 (1- (1- boundary)))))))
                  (should before) (should after) (should same)
                  (should (= (- (plist-get same :x) (plist-get before :x))
                             (plist-get large :pitch)))
                  (should (= (- (plist-get before :x) (plist-get after :x))
                             (+ (plist-get large :pitch) (plist-get large :paper-gap)))))
                ;; Click several real rendered cells, including the last row
                ;; and last visible column, then check the native caret.
                (dolist (offset (list 0 3 (1- (plist-get large :capacity))))
                  (let* ((target (+ (* 20 (+ first offset)) 20))
                         (pixel (tategaki-position-pixel target))
                         (top (+ (window-header-line-height) (window-tab-line-height)))
                         (hit (and pixel (posn-at-x-y (+ (plist-get pixel :x) 1)
                                                      (+ top (plist-get pixel :y) 1)))))
                    (should hit)
                    (should (>= (plist-get pixel :x) 0))
                    (should (<= (+ (plist-get pixel :x) (plist-get pixel :width))
                                (window-body-width nil t)))
                    (should (<= (+ (plist-get pixel :y) (plist-get pixel :height))
                                (window-body-height nil t)))
                    (tategaki-mouse-set-point (list 'mouse-1 hit))
                    (should (= (point) target))
                    (tategaki-rich-gui--caret)
                    (should (= tategaki--page first)))))
              (dolist (page '(2 3 4))
                (tategaki-goto-page page)
                (should (= (point) (1+ (* (1- page) 400))))
                (should (= page (plist-get (tategaki-manuscript-page-info tategaki--layout (point)) :current)))
                (tategaki-rich-gui--caret))
              (should (equal text (buffer-string)))
              (should (= tick (buffer-chars-modified-tick)))
              (should (eq undo buffer-undo-list))
              (should-not (buffer-modified-p)))))
      (set-frame-size nil width height))))

(ert-deftest tategaki-rich-gui-native-ime-preview-wraps-without-source-edit ()
  (tategaki-rich-gui--with-text "前後"
    (setq-local tategaki-column-height 3)
    (goto-char 2)
    (setq ns-working-text "日本語入力")
    (let (coordinates)
      (dotimes (index (length ns-working-text))
        (ns-put-marked-text (list 'ns-put-marked-text index 1))
        (let* ((object (tategaki-rich-gui--caret))
               (properties (text-properties-at (cdr object) (car object)))
               (pixel (tategaki-position-pixel (point))))
          (should (= (plist-get properties 'tategaki-preedit-index) index))
          (should (memq 'ns-marked-text-face (plist-get properties 'face)))
          (push (cons (plist-get pixel :x) (plist-get pixel :y)) coordinates)))
      (setq coordinates (nreverse coordinates))
      (should (= (caar coordinates) (caadr coordinates)))
      (should (< (cdar coordinates) (cdadr coordinates)))
      (should (< (car (nth 2 coordinates)) (caar coordinates))))
    (should (equal (buffer-string) "前後"))
    (should-not (buffer-modified-p))
    (should-not buffer-undo-list)))

(ert-deftest tategaki-rich-gui-header-and-tab-lines-preserve-bottom-caret ()
  (tategaki-rich-gui--with-text (make-string 1300 ?字)
    ;; Large window chrome makes the last paper row fall beyond the old
    ;; scan's body-height boundary when interpreted as posn-at-x-y input.
    (setq-local header-line-format (propertize "Header" 'face '(:height 4.0))
                tab-line-format (propertize "Tab" 'face '(:height 2.0)))
    (force-mode-line-update)
    (redisplay t)
    (tategaki-manuscript-set-preset "40x30")
    (goto-char 40)
    (tategaki-rich-gui--caret)
    (let* ((pixel (tategaki-position-pixel (point)))
           (top (+ (window-header-line-height) (window-tab-line-height))))
      (should (> (window-header-line-height) 0))
      (should (> (window-tab-line-height) 0))
      (should (> (+ top (plist-get pixel :y)) (window-body-height nil t)))
      (should (<= (+ (plist-get pixel :y) (plist-get pixel :height))
                  (window-body-height nil t))))
    (should-not (buffer-modified-p))
    (should-not buffer-undo-list)))

(ert-deftest tategaki-rich-gui-real-copilot-preview-and-native-accept-undo ()
  (tategaki-rich-gui--with-text "前後"
    (goto-char 2)
    (copilot--display-overlay-completion "12日本語" nil "12日本語" 2 2)
    (let* ((object (tategaki-rich-gui--caret))
           (face (get-text-property (cdr object) 'face (car object))))
      (should (eq tategaki--preview-kind 'copilot))
      (should (memq 'copilot-overlay-face face)))
    (should (equal (buffer-string) "前後"))
    (should-not buffer-undo-list)
    (copilot-accept-completion)
    (tategaki-refresh)
    (should (equal (buffer-string) "前12日本語後"))
    (undo-boundary)
    (undo-only 1)
    (tategaki-refresh)
    (should (equal (buffer-string) "前後"))))

(ert-deftest tategaki-rich-gui-real-corfu-popup-tracks-composed-caret ()
  (tategaki-rich-gui--with-text "前日本後"
    (goto-char 4)
    (corfu-mode 1)
    (setq corfu--candidates '("日本語入力候補") corfu--index 0)
    (corfu--preview-current 2 4)
    (tategaki-rich-gui--caret)
    (corfu--popup-show (posn-at-point) 7 12 '("日本語入力候補" "日本語入力確認") 0)
    (redisplay t)
    (let* ((pixel (tategaki-position-pixel (point)))
           (geometry (frame-parameter corfu--frame 'corfu--geometry))
           (edges (window-inside-pixel-edges)))
      (should (frame-live-p corfu--frame))
      (should (frame-visible-p corfu--frame))
      (should (= (cadr geometry)
                 (+ (cadr edges) (plist-get pixel :y)
                    (max (default-line-height) (plist-get pixel :height)))))
      ;; Corfu aligns the candidate text, not its left fringe, to point.
      ;; At the right edge it instead keeps the entire child frame visible.
      (with-current-buffer (window-buffer (frame-root-window corfu--frame))
        (let* ((cw (default-font-width))
               (left (min 16 (ceiling (* cw corfu-left-margin-width))))
               (right (min 16 (ceiling (* cw corfu-right-margin-width))))
               (text-x (+ (car geometry) left corfu-border-width))
               (right-edge (+ (car geometry) (nth 2 geometry) left right
                              (* 2 corfu-border-width))))
          (should (or (= text-x (+ (car edges) (plist-get pixel :x)))
                      (= right-edge (frame-pixel-width
                                     (frame-parent corfu--frame))))))))
    (should (equal (buffer-string) "前日本後"))
    (should-not (buffer-modified-p))))

(ert-deftest tategaki-rich-gui-studio-ime-corfu-copilot-priority-and-undo ()
  (require 'tategaki-studio)
  (tategaki-rich-gui--with-text "前日本後"
    (let ((tategaki-history-enabled nil)) (tategaki-studio-mode 1))
    (goto-char 4)
    (corfu-mode 1)
    (copilot--display-overlay-completion "語の続き" nil "語の続き" 4 4)
    (tategaki-rich-gui--caret)
    (should (eq tategaki--preview-kind 'copilot))
    (setq corfu--candidates '("日本語候補") corfu--index 0)
    (corfu--preview-current 2 4)
    (tategaki-rich-gui--caret)
    (should (eq tategaki--preview-kind 'corfu))
    (corfu--popup-show (posn-at-point) 7 12 '("日本語候補" "日本語確認") 0)
    (setq ns-working-text "にほんご")
    (ns-put-marked-text (list 'ns-put-marked-text 2 1))
    (tategaki-rich-gui--caret)
    (should (eq tategaki--preview-kind 'ime))
    (should (equal (buffer-string) "前日本後"))
    (should-not buffer-undo-list)
    (should-not (buffer-modified-p))
    (ns-delete-working-text)
    (setq ns-working-text "")
    (tategaki-rich-gui--caret)
    (should (eq tategaki--preview-kind 'corfu))
    (corfu--preview-delete)
    (when (frame-live-p corfu--frame) (make-frame-invisible corfu--frame))
    (tategaki-rich-gui--caret)
    (should (eq tategaki--preview-kind 'copilot))
    (copilot-accept-completion)
    (should (equal (buffer-string) "前日本語の続き後"))
    (undo-boundary) (undo-only 1)
    (should (equal (buffer-string) "前日本後"))
    (tategaki-studio-mode -1)))

(run-at-time 120 nil (lambda () (kill-emacs 2)))
(run-at-time
 1 nil
 (lambda ()
   (let ((status 2))
     (condition-case err
         (progn
           (unless (and (display-graphic-p) (featurep 'ns))
             (error "Rich integration requires dedicated NS Emacs"))
           (set-frame-parameter nil 'name "TATEGAKI RICH INTEGRATION")
           (delete-other-windows)
           (set-frame-size nil 100 40)
           (let ((stats (ert-run-tests-batch "^tategaki-rich-gui-")))
             (setq status (if (and (= (ert-stats-completed-expected stats) 12)
                                  (zerop (ert-stats-completed-unexpected stats))
                                  (zerop (ert-stats-skipped stats))) 0 1))))
       (error (message "Rich GUI setup failure: %S" err)))
     (with-current-buffer "*Messages*"
       (write-region (point-min) (point-max)
                     (expand-file-name "tategaki-typeset-gui-tests.log" temporary-file-directory)))
     (kill-emacs status))))

;;; tategaki-typeset-graphical-tests.el ends here
