;;; tategaki_live_extraction.el --- Opt-in local-model smoke test -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
;; Run explicitly with Emacs -Q --batch -l this-file.  Uses only synthetic text.
;; TATEGAKI_LIVE_MODEL must identify an already loaded local chat model.
;; Optional TATEGAKI_LIVE_ENDPOINT, TATEGAKI_LIVE_OUTPUT select URL/output directory.
;; The response count is model-dependent; evidence/state invariants are strict.
(setq load-prefer-newer t)
(add-to-list 'load-path (expand-file-name "../.." (file-name-directory (or load-file-name buffer-file-name))))
(defvar tategaki-live-extraction-output
  (or (getenv "TATEGAKI_LIVE_OUTPUT") (make-temp-file "tategaki-live-extraction-" t)))
(make-directory tategaki-live-extraction-output t)
(unless (getenv "TATEGAKI_LIVE_MODEL")
  (error "Set TATEGAKI_LIVE_MODEL to an already loaded local model"))
(princ (format "Artifacts: %s\n" tategaki-live-extraction-output))
(require 'tategaki-world)
(require 'tategaki-timeline)
(require 'tategaki-foreshadow)
(setq tategaki-ai-enabled t tategaki-ai-provider 'lm-studio
      tategaki-ai-model (getenv "TATEGAKI_LIVE_MODEL")
      tategaki-ai-endpoint (or (getenv "TATEGAKI_LIVE_ENDPOINT") "http://127.0.0.1:1234/v1") tategaki-ai-timeout 120)
(let ((original-chat (symbol-function 'tategaki-ai-chat)) responses results)
  (cl-letf (((symbol-function 'tategaki-ai-chat)
             (lambda (messages callback &optional authorized)
               (funcall original-chat messages
                        (lambda (result)
                          (push (list :messages (vconcat messages) :response result) responses)
                          (funcall callback result)) authorized))))
    (with-temp-buffer
      (rename-buffer "*Tategaki synthetic live extraction*")
      (text-mode)
      (insert "第1章\n2026年9月29日08時、花子（愛称ハナ）は城へ着いた。花子は門番から「青い鍵は古い箱の中だ」と聞き、鍵の場所を知った。花子にはまだ箱を開ける理由がわからない。\n\n翌日の08時、花子は古い箱から青い鍵を取り出した。鍵で地下室の扉を開け、行方不明の妹を発見した。\n")
      (goto-char 1) (buffer-enable-undo) (set-buffer-modified-p nil)
      (let ((text (buffer-string)) (undo buffer-undo-list) (position (point)))
        (dolist (kind '(world timeline foreshadow))
          (let ((pending t) completed)
            (pcase kind
              ('world (tategaki-world-extract t (lambda (result) (setq completed result pending nil))))
              ('timeline (tategaki-timeline-extract nil (lambda (result) (setq completed result pending nil))))
              ('foreshadow (tategaki-foreshadow-extract nil (lambda (result) (setq completed result pending nil)))))
            (while pending (accept-process-output nil 0.05))
            (push (cons kind completed) results)
            (princ (format "%s: %S\n" kind completed))))
        (let* ((world (tategaki-world-records)) (times (tategaki-timeline-records))
               (threads (tategaki-foreshadow-records)) decisions)
          (with-temp-file (expand-file-name "raw-result.json" tategaki-live-extraction-output)
            (insert (json-encode (list :results results :responses (vconcat (nreverse responses))
                                      :world (vconcat world) :timeline (vconcat times) :foreshadow (vconcat threads)))))
          (unless (cl-every (lambda (entry) (and (plist-get (cdr entry) :ok) (> (plist-get (cdr entry) :count) 0))) results)
            (error "Extraction failed or no candidates: %S" results))
          (unless (and (cl-every (lambda (record) (equal (plist-get record :state) "inferred")) world)
                       (cl-every (lambda (record) (equal (plist-get record :state) "inferred")) times)
                       (cl-every (lambda (record) (equal (plist-get record :status) "candidate")) threads)
                       (cl-every (lambda (record) (tategaki-world-reference-valid-p (plist-get record :source)))
                                 (append world times threads)))
            (error "Candidate state/provenance invalid"))
          (let ((record (or (car (tategaki-world-records "Fact")) (car world))))
            (tategaki-world-set-state (plist-get record :id) "author-confirmed")
            (push (list :world-adopted (plist-get record :name)) decisions))
          (let ((anchor (cl-find "exact" times :key (lambda (record) (plist-get record :time-status)) :test #'equal))
                (relative (cl-find "relative" times :key (lambda (record) (plist-get record :time-status)) :test #'equal)))
            (unless (and anchor relative) (error "Expected exact and relative date proposals"))
            (tategaki-timeline-set-state (plist-get anchor :id) "author-confirmed")
            (tategaki-timeline-set-state (plist-get relative :id) "author-confirmed")
            (push (list :timeline-context (tategaki-timeline-context)) decisions))
          (let* ((payoff (cl-find "payoff" threads :key (lambda (record) (plist-get record :candidate-kind)) :test #'equal))
                 (setup (and payoff (cl-find (plist-get payoff :target-id) threads :key (lambda (record) (plist-get record :id)) :test #'equal))))
            (unless (and setup payoff) (error "Expected matched setup and payoff proposals"))
            (tategaki-foreshadow-adopt (plist-get setup :id))
            (tategaki-foreshadow-adopt (plist-get payoff :id) (plist-get setup :id))
            (push (list :foreshadow-resolved (plist-get setup :name) :payoff (plist-get payoff :name)) decisions))
          (unless (and (equal text (buffer-string)) (equal undo buffer-undo-list)
                       (= position (point)) (not (buffer-modified-p)))
            (error "Source state changed"))
          (let ((verified (list :source-unchanged t :decisions (vconcat decisions)
                                :world (vconcat (tategaki-world-records))
                                :timeline (vconcat (tategaki-timeline-records))
                                :foreshadow (vconcat (tategaki-foreshadow-records)))))
            (with-temp-file (expand-file-name "verified-result.json" tategaki-live-extraction-output)
              (insert (json-encode verified))))
          (princ "VERIFIED: actual local model candidates, exact provenance, explicit adoption, source text/point/undo/modified invariant.\n"))))))
