;;; tategaki-export-test.el --- Asynchronous export tests -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'tategaki-export)

(ert-deftest tategaki-export-async-argument-vector-and-immutable-snapshot ()
  (let* ((tategaki-export-program "/tmp/日本 語/tategaki-export")
         (tategaki-export-output-directory "/tmp/出力 結果")
         (tategaki-export--jobs (make-hash-table :test #'equal))
         (tategaki-export--last-job nil) captured id snapshot-file
         (fake-process 'export-test-process))
    (unwind-protect
        (with-temp-buffer
          (insert "未保存の｜漢字《かんじ》")
          (cl-letf (((symbol-function 'file-executable-p) (lambda (_) t))
                    ((symbol-function 'executable-find) (lambda (_) "/tmp/docker"))
                    ((symbol-function 'make-process) (lambda (&rest args) (setq captured args) fake-process))
                    ((symbol-function 'process-put) (lambda (&rest _args) nil)))
            (setq id (tategaki-export '("txt" "epub") "preview" 'full)))
          (let ((command (plist-get captured :command)))
            (should (equal (car command) "/tmp/日本 語/tategaki-export"))
            (should (member "/tmp/出力 結果" command))
            (should (member "txt,epub" command))
            (should-not (member "sh" command))
            (setq snapshot-file (nth 2 command)))
          (insert "追加")
          (with-temp-buffer
            (insert-file-contents snapshot-file)
            (should (equal (buffer-string) "未保存の｜漢字《かんじ》"))))
      (when id
        (let ((job (gethash id tategaki-export--jobs)))
          (delete-directory (plist-get job :snapshot-directory) t)
          (kill-buffer (plist-get job :buffer)))))))

(ert-deftest tategaki-export-no-docker-is-clear-error ()
  (cl-letf (((symbol-function 'file-executable-p) (lambda (_) t))
            ((symbol-function 'executable-find) (lambda (_) nil)))
    (should-error (tategaki-export '("txt") "preview") :type 'user-error)))

(ert-deftest tategaki-export-cannot-cancel-external-job ()
  (let ((tategaki-export--jobs (make-hash-table :test #'equal)))
    (should-error (tategaki-export-cancel "external-job") :type 'user-error)))

(ert-deftest tategaki-export-cancel-own-job-only ()
  (let ((tategaki-export--jobs (make-hash-table :test #'equal)) captured)
    (puthash "mine" (list :state 'running :buffer "*mine*") tategaki-export--jobs)
    (cl-letf (((symbol-function 'make-process) (lambda (&rest args) (setq captured args))))
      (tategaki-export-cancel "mine"))
    (should (equal (plist-get captured :command) (list tategaki-export-program "cancel" "mine")))
    (should (plist-get (gethash "mine" tategaki-export--jobs) :cancel-requested))
    (kill-buffer (plist-get (gethash "mine" tategaki-export--jobs) :cancel-buffer))))

(ert-deftest tategaki-export-cancel-retries-while-own-container-starts ()
  (let ((tategaki-export--jobs (make-hash-table :test #'equal)) captured retry)
    (puthash "mine" (list :state 'running :process 'launcher :buffer "*mine*") tategaki-export--jobs)
    (cl-letf (((symbol-function 'make-process) (lambda (&rest args) (setq captured args) 'cancel-process))
              ((symbol-function 'process-status) (lambda (_) 'exit))
              ((symbol-function 'process-exit-status) (lambda (_) 1))
              ((symbol-function 'process-live-p) (lambda (process) (eq process 'launcher)))
              ((symbol-function 'run-at-time) (lambda (&rest args) (setq retry args) 'retry-timer)))
      (tategaki-export-cancel "mine")
      (funcall (plist-get captured :sentinel) 'cancel-process "No such container"))
    (should (plist-get (gethash "mine" tategaki-export--jobs) :cancel-requested))
    (should (eq #'tategaki-export--cancel-attempt (nth 2 retry)))
    (should (equal "mine" (nth 3 retry)))))

(ert-deftest tategaki-export-cancel-startup-retry-is-bounded ()
  (let ((tategaki-export--jobs (make-hash-table :test #'equal)) captured)
    (puthash "mine" (list :state 'running :process 'launcher :buffer "*mine*" :cancel-requested t)
             tategaki-export--jobs)
    (cl-letf (((symbol-function 'make-process) (lambda (&rest args) (setq captured args) 'cancel-process))
              ((symbol-function 'process-status) (lambda (_) 'exit))
              ((symbol-function 'process-exit-status) (lambda (_) 1))
              ((symbol-function 'process-live-p) (lambda (process) (eq process 'launcher))))
      (tategaki-export--cancel-attempt "mine" (- (float-time) 1))
      (funcall (plist-get captured :sentinel) 'cancel-process "No such container"))
    (should-not (plist-get (gethash "mine" tategaki-export--jobs) :cancel-requested))))

(ert-deftest tategaki-export-profile-input-and-metadata-inheritance ()
  (let* ((dir (make-temp-file "tategaki-export-profile-" t))
         (profile (expand-file-name "custom.json" dir))
         (tategaki-export--jobs (make-hash-table :test #'equal))
         (tategaki-export-input-options nil)
         (tategaki-export-metadata '((author . "筆名")))
         captured id)
    (unwind-protect
        (progn
          (tategaki-export-model-write-json
           '((input . ((headings . "markdown"))) (metadata . ((title . "題名") (author . "profile")))) profile)
          (with-temp-buffer
            (insert "# 章\n本文")
            (cl-letf (((symbol-function 'file-executable-p) (lambda (_) t))
                      ((symbol-function 'executable-find) (lambda (_) "/tmp/docker"))
                      ((symbol-function 'make-process) (lambda (&rest args) (setq captured args) 'test-process))
                      ((symbol-function 'process-put) (lambda (&rest _args) nil)))
              (setq id (tategaki-export '("txt") profile 'full))))
          (let* ((json-object-type 'alist) (json-key-type 'symbol)
                 (model (json-read-file (nth 4 (plist-get captured :command)))))
            (should (equal "題名" (alist-get 'title (alist-get 'metadata model))))
            (should (equal "筆名" (alist-get 'author (alist-get 'metadata model))))
            (should (equal "heading" (alist-get 'type (aref (alist-get 'blocks model) 0))))))
      (when id
        (let ((job (gethash id tategaki-export--jobs)))
          (delete-directory (plist-get job :snapshot-directory) t)
          (kill-buffer (plist-get job :buffer))))
      (delete-directory dir t))))

(ert-deftest tategaki-export-cancel-launch-failure-does-not-mark-cancelled ()
  (let ((tategaki-export--jobs (make-hash-table :test #'equal)))
    (puthash "mine" (list :state 'running :buffer "*mine*") tategaki-export--jobs)
    (cl-letf (((symbol-function 'make-process) (lambda (&rest _) (error "Could not launch"))))
      (should-error (tategaki-export-cancel "mine")))
    (should-not (plist-get (gethash "mine" tategaki-export--jobs) :cancel-requested))))

(ert-deftest tategaki-export-sentinel-does-not-confuse-success-and-cancel-request ()
  (let ((tategaki-export--jobs (make-hash-table :test #'equal)))
    (puthash "mine" (list :state 'running :cancel-requested t :buffer "*mine*"
                         :snapshot-directory "/nonexistent-tategaki-snapshot" :directory "/tmp/result")
             tategaki-export--jobs)
    (cl-letf (((symbol-function 'process-status) (lambda (_) 'exit))
              ((symbol-function 'process-exit-status) (lambda (_) 0))
              ((symbol-function 'process-get) (lambda (&rest _) "mine")))
      (tategaki-export--sentinel 'test-process "finished"))
    (should (eq 'succeeded (plist-get (gethash "mine" tategaki-export--jobs) :state)))))

(provide 'tategaki-export-test)
